/**
 * The tour — real screens of Daakia, with the interesting parts marked.
 *
 * ── What this is ──
 *
 * Every other wiki page is reference: paragraphs you read when you already
 * know what you are looking for. This is the other thing — a walk through the
 * app for somebody who has never opened it, built the way a product tour is:
 * a real screenshot, a few numbered points on it, and one sentence per point
 * that answers "what is that?".
 *
 * ── Why coordinates and not anchors ──
 *
 * A stop's picture is a captured `#root` outerHTML rendered at a fixed design
 * size (1280×720 — see CaptureScrollView). Hotspots are placed as percentages
 * of that box, so they stay put when the frame is scaled to whatever width the
 * reader's panel happens to be. Anchoring to elements inside the capture would
 * tie every hotspot to a class name that a restyle can rename.
 *
 * ── Keeping it honest ──
 *
 * Coordinates are measured, not guessed: each one was read off the rendered
 * capture in the running app, so a marker sits on the thing it names rather
 * than near it.
 *
 * `capture` is a screen id from `scripts/screen-catalogue.mjs`. `tour.test.ts`
 * fails if a stop names a capture that no longer exists, so a recapture that
 * drops a screen shows up here rather than as a blank frame.
 */

export interface Hotspot {
  /**
   * Text to find inside the capture, and pin the marker to.
   *
   * Preferred over coordinates: a recapture moves things, and a marker that
   * finds its own anchor moves with them. Ninety screens is also more than
   * anyone will re-measure by hand after a restyle.
   *
   * Matched against the trimmed text of leaf elements, first exact then
   * prefix. If nothing matches, `x`/`y` are used, and if those are absent the
   * marker is dropped rather than parked in a corner claiming to point at
   * something.
   */
  anchor?: string;
  /** Which of several matches — the tab bar has many "SOAP"s. Default 0. */
  nth?: number;
  /** Nudge off the anchor's centre, in percent, once it is found. */
  dx?: number;
  dy?: number;
  /** Percentage across the captured frame, 0–100. Fallback for `anchor`. */
  x?: number;
  /** Percentage down the captured frame, 0–100. */
  y?: number;
  title: string;
  body: string;
}

export interface TourStop {
  id: string;
  /** Capture id — the filename in `plan/daakia_live/<section>/` without .html. */
  capture: string;
  /** Which section's captures module holds it. */
  section: 'rest' | 'graphql' | 'grpc' | 'soap' | 'realtime' | 'mock-server' | 'platform' | 'dk8s';
  chapter: string;
  title: string;
  blurb: string;
  hotspots: Hotspot[];
}

export const TOUR_STOPS: TourStop[] = [
  {
    id: 'tour-rest-params',
    capture: 'rest-params',
    section: 'rest',
    chapter: 'REST',
    title: 'Everything about one request, on one screen',
    blurb: 'A request in Daakia is a tab. The URL bar runs across the top, everything that shapes the call sits in the row of sub-tabs beneath it, and the answer lands in the panel below — no dialogs, no second window.',
    hotspots: [
      { anchor: 'REST', title: 'Protocol rail',
        body: 'REST, GraphQL, WebSocket, gRPC, SOAP, MCP, the mock server and dk8s. Picking one switches which kind of tab the + button opens.' },
      { anchor: 'Untitled Request', title: 'The tab bar',
        body: 'Every request you have open, colour-dotted by protocol. An orange dot means unsaved. Right-click for rename, duplicate, close others.' },
      { anchor: 'Send', title: 'Send',
        body: 'Or Ctrl+Enter. {{variables}} from the active environment resolve just before the call goes out, so what you see is what is sent.' },
      { anchor: 'Params', title: 'Request sub-tabs',
        body: 'Params, Headers, Body, Authorization, Scripts, Variables, Action, Docs and Settings. A dot on a tab means it has something in it, so you can see what a request carries without opening each one.' },
    ],
  },
  {
    id: 'tour-rest-headers',
    capture: 'rest-headers',
    section: 'rest',
    chapter: 'REST',
    title: 'Headers, and where they come from',
    blurb: 'The same key/value table as params, plus everything inherited from the collection and the environment — shown, not hidden, so a header you did not type is still a header you can see.',
    hotspots: [
      { anchor: 'Headers', title: 'Headers tab',
        body: 'The count beside the name is how many are enabled, so an accidental extra header is visible from the tab itself.' },
      { anchor: 'Send', title: 'Send',
        body: 'Or Ctrl+Enter. Any {{variables}} in the URL, headers or body resolve against the active environment just before the call goes out.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
    ],
  },
  {
    id: 'tour-rest-body-json',
    capture: 'rest-body-json',
    section: 'rest',
    chapter: 'REST',
    title: 'A body with an editor that understands it',
    blurb: 'JSON, XML, form-data, url-encoded, binary or GraphQL. The editor knows which one it is holding, so it folds, highlights and complains about syntax in the right language.',
    hotspots: [
      { anchor: 'Body', title: 'Body tab',
        body: 'Nine content types. Picking one switches both the editor language and the Content-Type header, so the two cannot disagree.' },
      { anchor: 'JSON', title: 'Content type',
        body: 'Set explicitly, or overridden per-request. The dropdown lists what Daakia knows how to render, and anything else your API needs can be typed in.' },
      { anchor: 'Send', title: 'Send',
        body: 'Or Ctrl+Enter. Any {{variables}} in the URL, headers or body resolve against the active environment just before the call goes out.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
    ],
  },
  {
    id: 'tour-rest-auth',
    capture: 'rest-auth',
    section: 'rest',
    chapter: 'REST',
    title: 'Auth, per request or inherited',
    blurb: 'Bearer, Basic, API key, OAuth 2.0 and Digest. Set it here, or leave it inheriting from the collection so a token lives in one place instead of on forty requests.',
    hotspots: [
      { anchor: 'Authorization', title: 'Authorization tab',
        body: 'A request either carries its own auth or inherits — and the tab says which, so an unauthenticated call is not a mystery.' },
      { anchor: 'Send', title: 'Send',
        body: 'Or Ctrl+Enter. Any {{variables}} in the URL, headers or body resolve against the active environment just before the call goes out.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
    ],
  },
  {
    id: 'tour-rest-scripts',
    capture: 'rest-scripts',
    section: 'rest',
    chapter: 'REST',
    title: 'Scripts before and after',
    blurb: 'JavaScript that runs around the request: set up a token before, assert on the answer after. The same dk.* runtime as every other protocol.',
    hotspots: [
      { anchor: 'Scripts', title: 'Scripts tab',
        body: 'Pre-request and post-response, each its own editor with autocomplete over the dk.* API.' },
      { anchor: 'Send', title: 'Send',
        body: 'Or Ctrl+Enter. Any {{variables}} in the URL, headers or body resolve against the active environment just before the call goes out.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
    ],
  },
  {
    id: 'tour-rest-variables',
    capture: 'rest-variables',
    section: 'rest',
    chapter: 'REST',
    title: 'Variables, narrowest wins',
    blurb: 'Request variables beat collection variables beat environment variables. One request can pin a value without disturbing anything else.',
    hotspots: [
      { anchor: 'Variables', title: 'Variables tab',
        body: 'Scoped to this request. Useful for the one call that needs a different id while the rest of the collection stays as it is.' },
      { anchor: 'Send', title: 'Send',
        body: 'Or Ctrl+Enter. Any {{variables}} in the URL, headers or body resolve against the active environment just before the call goes out.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
    ],
  },
  {
    id: 'tour-rest-response',
    capture: 'rest-response',
    section: 'rest',
    chapter: 'REST',
    title: 'The response, with the evidence attached',
    blurb: 'Status, timing and size on one line; the body, the headers, the cookies and the connection timeline underneath.',
    hotspots: [
      { anchor: 'Response Body', title: 'Body viewer',
        body: 'Syntax-highlighted and foldable, with a filter box for JSONPath or XPath. Right-click anything here to compare it against your clipboard.' },
      { anchor: 'Timeline', title: 'Timeline',
        body: 'DNS, TCP, TLS and time-to-first-byte, which is how you tell a slow server from a slow network.' },
      { anchor: 'Save example', title: 'Save an example',
        body: 'Keeps this exact response with the request, so the next person sees what it is meant to return.' },
      { anchor: 'Send', title: 'Send',
        body: 'Or Ctrl+Enter. Any {{variables}} in the URL, headers or body resolve against the active environment just before the call goes out.' },
    ],
  },
  {
    id: 'tour-graphql-query',
    capture: 'graphql-query',
    section: 'graphql',
    chapter: 'GraphQL',
    title: 'GraphQL, with the schema in hand',
    blurb: 'A query editor that knows your schema: completion over the real types, and errors before you send rather than after.',
    hotspots: [
      { anchor: 'Query', title: 'Query editor',
        body: 'Autocomplete from the introspected schema, so field names come from the server rather than from memory.' },
      { anchor: 'Query Builder', title: 'Query Builder',
        body: 'Build a query by picking fields, or describe what you want and let AI draft it.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
    ],
  },
  {
    id: 'tour-graphql-variables',
    capture: 'graphql-variables',
    section: 'graphql',
    chapter: 'GraphQL',
    title: 'Variables as their own document',
    blurb: 'GraphQL separates the query from its inputs, and so does this — a JSON document validated against the variables the query declares.',
    hotspots: [
      { anchor: 'Variables', title: 'Variables tab',
        body: 'Checked against the query: a variable the query never declares is flagged before the request goes out.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
      { anchor: 'No Environment', title: 'Environment picker',
        body: 'The environment supplying {{variables}} right now. Going from local to staging is this dropdown rather than an edit to every request.' },
    ],
  },
  {
    id: 'tour-graphql-headers',
    capture: 'graphql-headers',
    section: 'graphql',
    chapter: 'GraphQL',
    title: 'Headers on a GraphQL endpoint',
    blurb: 'One endpoint, many operations — so headers, auth and scripts work exactly as they do on REST.',
    hotspots: [
      { anchor: 'Headers', title: 'Headers tab',
        body: 'The same table as every other protocol. There is one editor to learn, not six.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
      { anchor: 'No Environment', title: 'Environment picker',
        body: 'The environment supplying {{variables}} right now. Going from local to staging is this dropdown rather than an edit to every request.' },
    ],
  },
  {
    id: 'tour-graphql-authorization',
    capture: 'graphql-authorization',
    section: 'graphql',
    chapter: 'GraphQL',
    title: 'Auth for GraphQL',
    blurb: 'The same auth editor as REST, because the transport is the same.',
    hotspots: [
      { anchor: 'Authorization', title: 'Authorization tab',
        body: 'Bearer, Basic, API key, OAuth 2.0 — inherited from the collection unless this request pins its own.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
      { anchor: 'No Environment', title: 'Environment picker',
        body: 'The environment supplying {{variables}} right now. Going from local to staging is this dropdown rather than an edit to every request.' },
    ],
  },
  {
    id: 'tour-graphql-scripts',
    capture: 'graphql-scripts',
    section: 'graphql',
    chapter: 'GraphQL',
    title: 'Scripts on a GraphQL call',
    blurb: 'The dk.* runtime again — refresh a token before, assert on data or errors after.',
    hotspots: [
      { anchor: 'Scripts', title: 'Scripts tab',
        body: 'A GraphQL 200 can still carry errors, so asserting that the errors array is empty is the check that matters here.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
      { anchor: 'No Environment', title: 'Environment picker',
        body: 'The environment supplying {{variables}} right now. Going from local to staging is this dropdown rather than an edit to every request.' },
    ],
  },
  {
    id: 'tour-graphql-subscription',
    capture: 'graphql-subscription',
    section: 'graphql',
    chapter: 'GraphQL',
    title: 'Subscriptions over graphql-ws',
    blurb: 'A live subscription in the same tab as the query, with the events it produces logged as they arrive.',
    hotspots: [
      { anchor: 'Subscription', title: 'Subscription tab',
        body: 'Subscribe, watch events land with timestamps, stop. The connection state is on screen rather than guessed at.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
      { anchor: 'No Environment', title: 'Environment picker',
        body: 'The environment supplying {{variables}} right now. Going from local to staging is this dropdown rather than an edit to every request.' },
    ],
  },
  {
    id: 'tour-graphql-response',
    capture: 'graphql-response',
    section: 'graphql',
    chapter: 'GraphQL',
    title: 'A GraphQL response',
    blurb: 'Status, data and errors — with errors flagged even on a 200, which is the case that catches people out.',
    hotspots: [
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
      { anchor: 'No Environment', title: 'Environment picker',
        body: 'The environment supplying {{variables}} right now. Going from local to staging is this dropdown rather than an edit to every request.' },
      { anchor: 'Collections', title: 'Collections',
        body: 'Saved requests in folders, with variables, headers and auth that everything inside inherits unless it overrides them.' },
    ],
  },
  {
    id: 'tour-grpc-proto',
    capture: 'grpc-proto',
    section: 'grpc',
    chapter: 'gRPC',
    title: 'gRPC starts with the service definition',
    blurb: 'Load a .proto or reflect off the server, and Daakia knows the services, the methods and the shape of every message.',
    hotspots: [
      { anchor: 'Proto', title: 'Service definition',
        body: 'From a file or from server reflection. Either way the method list below is the real one.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
      { anchor: 'No Environment', title: 'Environment picker',
        body: 'The environment supplying {{variables}} right now. Going from local to staging is this dropdown rather than an edit to every request.' },
    ],
  },
  {
    id: 'tour-grpc-message',
    capture: 'grpc-message',
    section: 'grpc',
    chapter: 'gRPC',
    title: 'The message, typed',
    blurb: 'A request body that is checked against the proto rather than being free-form JSON hoping to match.',
    hotspots: [
      { anchor: 'Message', title: 'Message editor',
        body: 'Completion and validation from the message type the selected method expects.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
      { anchor: 'No Environment', title: 'Environment picker',
        body: 'The environment supplying {{variables}} right now. Going from local to staging is this dropdown rather than an edit to every request.' },
    ],
  },
  {
    id: 'tour-grpc-metadata',
    capture: 'grpc-metadata',
    section: 'grpc',
    chapter: 'gRPC',
    title: 'Metadata instead of headers',
    blurb: 'gRPC calls them metadata; the editor is the key/value table you already know.',
    hotspots: [
      { anchor: 'Metadata', title: 'Metadata tab',
        body: 'Sent with the call. Binary-valued keys (-bin) are handled as gRPC requires.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
      { anchor: 'No Environment', title: 'Environment picker',
        body: 'The environment supplying {{variables}} right now. Going from local to staging is this dropdown rather than an edit to every request.' },
    ],
  },
  {
    id: 'tour-grpc-auth',
    capture: 'grpc-auth',
    section: 'grpc',
    chapter: 'gRPC',
    title: 'Auth on a gRPC channel',
    blurb: 'Per-call credentials, and TLS settings for the channel itself.',
    hotspots: [
      { anchor: 'Auth', title: 'Auth tab',
        body: 'Token or certificate. Channel TLS is separate from call credentials, and both live here.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
      { anchor: 'No Environment', title: 'Environment picker',
        body: 'The environment supplying {{variables}} right now. Going from local to staging is this dropdown rather than an edit to every request.' },
    ],
  },
  {
    id: 'tour-grpc-scripts',
    capture: 'grpc-scripts',
    section: 'grpc',
    chapter: 'gRPC',
    title: 'Scripts around a gRPC call',
    blurb: 'The same runtime once more, so an assertion reads the same whichever protocol produced the answer.',
    hotspots: [
      { anchor: 'Scripts', title: 'Scripts tab',
        body: 'Pre-call and post-call, with dk.response holding the decoded message.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
      { anchor: 'No Environment', title: 'Environment picker',
        body: 'The environment supplying {{variables}} right now. Going from local to staging is this dropdown rather than an edit to every request.' },
    ],
  },
  {
    id: 'tour-grpc-response-body',
    capture: 'grpc-response-body',
    section: 'grpc',
    chapter: 'gRPC',
    title: 'The decoded response',
    blurb: 'The message as the proto says it should be read, not as raw bytes.',
    hotspots: [
      { anchor: 'Response', title: 'Decoded message',
        body: 'Field names come from the proto, so the answer is readable without a decoder ring.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
      { anchor: 'No Environment', title: 'Environment picker',
        body: 'The environment supplying {{variables}} right now. Going from local to staging is this dropdown rather than an edit to every request.' },
    ],
  },
  {
    id: 'tour-grpc-response-metadata',
    capture: 'grpc-response-metadata',
    section: 'grpc',
    chapter: 'gRPC',
    title: 'Response metadata and trailers',
    blurb: 'Both halves — what came back with the headers and what came back at the end.',
    hotspots: [
      { anchor: 'Metadata', title: 'Metadata and trailers',
        body: 'Trailers carry the status details a failed call explains itself with.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
      { anchor: 'No Environment', title: 'Environment picker',
        body: 'The environment supplying {{variables}} right now. Going from local to staging is this dropdown rather than an edit to every request.' },
    ],
  },
  {
    id: 'tour-grpc-response-tests',
    capture: 'grpc-response-tests',
    section: 'grpc',
    chapter: 'gRPC',
    title: 'Assertions on a gRPC response',
    blurb: 'dk.test() results, listed pass and fail, for the call that just ran.',
    hotspots: [
      { anchor: 'Tests', title: 'Test results',
        body: 'Each assertion with its own line, so a failing one names itself rather than failing the whole call.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
      { anchor: 'No Environment', title: 'Environment picker',
        body: 'The environment supplying {{variables}} right now. Going from local to staging is this dropdown rather than an edit to every request.' },
    ],
  },
  {
    id: 'tour-grpc-response-timeline',
    capture: 'grpc-response-timeline',
    section: 'grpc',
    chapter: 'gRPC',
    title: 'Where a gRPC call spent its time',
    blurb: 'Connection, request, response — the same timeline REST gets.',
    hotspots: [
      { anchor: 'Timeline', title: 'Timeline',
        body: 'Useful on streaming calls, where "slow" usually means one slow phase rather than a slow server.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
      { anchor: 'No Environment', title: 'Environment picker',
        body: 'The environment supplying {{variables}} right now. Going from local to staging is this dropdown rather than an edit to every request.' },
    ],
  },
  {
    id: 'tour-soap-wsdl',
    capture: 'soap-wsdl',
    section: 'soap',
    chapter: 'SOAP',
    title: 'SOAP starts with the WSDL',
    blurb: 'Point at a WSDL and Daakia lists the services, ports and operations it declares.',
    hotspots: [
      { anchor: 'WSDL', title: 'WSDL browser',
        body: 'Services and operations from the document itself — no guessing at SOAPAction strings.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
      { anchor: 'No Environment', title: 'Environment picker',
        body: 'The environment supplying {{variables}} right now. Going from local to staging is this dropdown rather than an edit to every request.' },
    ],
  },
  {
    id: 'tour-soap-envelope',
    capture: 'soap-envelope',
    section: 'soap',
    chapter: 'SOAP',
    title: 'The envelope, or a form over it',
    blurb: 'Write the XML if you want to. Most of the time the generated form is faster and cannot produce a malformed envelope.',
    hotspots: [
      { anchor: 'Envelope', title: 'Envelope editor',
        body: 'The real XML, highlighted and validated. Namespaces are kept as the WSDL declares them.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
      { anchor: 'No Environment', title: 'Environment picker',
        body: 'The environment supplying {{variables}} right now. Going from local to staging is this dropdown rather than an edit to every request.' },
    ],
  },
  {
    id: 'tour-soap-form',
    capture: 'soap-form',
    section: 'soap',
    chapter: 'SOAP',
    title: 'A form built from the schema',
    blurb: 'Fields generated from the operation’s input type — fill them in and the envelope is assembled correctly.',
    hotspots: [
      { anchor: 'Form', title: 'Generated form',
        body: 'One field per element the schema declares, with its type enforced.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
      { anchor: 'No Environment', title: 'Environment picker',
        body: 'The environment supplying {{variables}} right now. Going from local to staging is this dropdown rather than an edit to every request.' },
    ],
  },
  {
    id: 'tour-soap-headers',
    capture: 'soap-headers',
    section: 'soap',
    chapter: 'SOAP',
    title: 'SOAP headers',
    blurb: 'Transport headers and SOAP headers are different things; both are editable here.',
    hotspots: [
      { anchor: 'Headers', title: 'Headers tab',
        body: 'HTTP headers for the transport. SOAP headers go in the envelope, where the schema expects them.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
      { anchor: 'No Environment', title: 'Environment picker',
        body: 'The environment supplying {{variables}} right now. Going from local to staging is this dropdown rather than an edit to every request.' },
    ],
  },
  {
    id: 'tour-soap-wssecurity',
    capture: 'soap-wssecurity',
    section: 'soap',
    chapter: 'SOAP',
    title: 'WS-Security, filled in for you',
    blurb: 'UsernameToken, timestamps, digests — assembled into the envelope rather than typed by hand.',
    hotspots: [
      { anchor: 'WS-Security', title: 'WS-Security',
        body: 'Password digest or plain text, with the nonce and timestamp generated per request.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
      { anchor: 'No Environment', title: 'Environment picker',
        body: 'The environment supplying {{variables}} right now. Going from local to staging is this dropdown rather than an edit to every request.' },
    ],
  },
  {
    id: 'tour-soap-authorization',
    capture: 'soap-authorization',
    section: 'soap',
    chapter: 'SOAP',
    title: 'Transport auth for SOAP',
    blurb: 'The auth editor again, for services that want HTTP auth as well as WS-Security.',
    hotspots: [
      { anchor: 'Authorization', title: 'Authorization tab',
        body: 'Sits alongside WS-Security rather than instead of it — plenty of services want both.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
      { anchor: 'No Environment', title: 'Environment picker',
        body: 'The environment supplying {{variables}} right now. Going from local to staging is this dropdown rather than an edit to every request.' },
    ],
  },
  {
    id: 'tour-soap-attachments',
    capture: 'soap-attachments',
    section: 'soap',
    chapter: 'SOAP',
    title: 'MTOM attachments',
    blurb: 'Files carried alongside the envelope, which is how SOAP moves anything binary.',
    hotspots: [
      { anchor: 'Attachments', title: 'Attachments tab',
        body: 'Each part with its content type and its reference in the envelope.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
      { anchor: 'No Environment', title: 'Environment picker',
        body: 'The environment supplying {{variables}} right now. Going from local to staging is this dropdown rather than an edit to every request.' },
    ],
  },
  {
    id: 'tour-soap-assertions',
    capture: 'soap-assertions',
    section: 'soap',
    chapter: 'SOAP',
    title: 'Assertions on the envelope',
    blurb: 'XPath assertions over the response, checked automatically after every send.',
    hotspots: [
      { anchor: 'Assertions', title: 'Assertions tab',
        body: 'XPath rather than JSONPath, because the answer is XML.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
      { anchor: 'No Environment', title: 'Environment picker',
        body: 'The environment supplying {{variables}} right now. Going from local to staging is this dropdown rather than an edit to every request.' },
    ],
  },
  {
    id: 'tour-soap-scripts',
    capture: 'soap-scripts',
    section: 'soap',
    chapter: 'SOAP',
    title: 'Scripts around a SOAP call',
    blurb: 'The same runtime as everywhere else, with the envelope available as text and as parsed XML.',
    hotspots: [
      { anchor: 'Scripts', title: 'Scripts tab',
        body: 'Pre-request and post-response, identical in shape to REST.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
      { anchor: 'No Environment', title: 'Environment picker',
        body: 'The environment supplying {{variables}} right now. Going from local to staging is this dropdown rather than an edit to every request.' },
    ],
  },
  {
    id: 'tour-soap-response-body',
    capture: 'soap-response-body',
    section: 'soap',
    chapter: 'SOAP',
    title: 'The response envelope',
    blurb: 'Highlighted XML, foldable, with faults called out rather than buried.',
    hotspots: [
      { anchor: 'Response', title: 'Response body',
        body: 'A SOAP fault is still an HTTP 200, so the fault is surfaced here rather than left to the status code.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
      { anchor: 'No Environment', title: 'Environment picker',
        body: 'The environment supplying {{variables}} right now. Going from local to staging is this dropdown rather than an edit to every request.' },
    ],
  },
  {
    id: 'tour-soap-response-headers',
    capture: 'soap-response-headers',
    section: 'soap',
    chapter: 'SOAP',
    title: 'Response headers',
    blurb: 'What came back on the transport, separate from what came back in the envelope.',
    hotspots: [
      { anchor: 'Headers', title: 'Response headers',
        body: 'The transport half of the answer.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
      { anchor: 'No Environment', title: 'Environment picker',
        body: 'The environment supplying {{variables}} right now. Going from local to staging is this dropdown rather than an edit to every request.' },
    ],
  },
  {
    id: 'tour-soap-response-tests',
    capture: 'soap-response-tests',
    section: 'soap',
    chapter: 'SOAP',
    title: 'Assertion results',
    blurb: 'Which XPath assertions passed, and what the failing ones actually found.',
    hotspots: [
      { anchor: 'Tests', title: 'Test results',
        body: 'A failed assertion shows the value it got, which is the thing you need to fix it.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
      { anchor: 'No Environment', title: 'Environment picker',
        body: 'The environment supplying {{variables}} right now. Going from local to staging is this dropdown rather than an edit to every request.' },
    ],
  },
  {
    id: 'tour-ws-communication',
    capture: 'ws-communication',
    section: 'realtime',
    chapter: 'Realtime',
    title: 'WebSocket, both directions',
    blurb: 'Connect, send, and watch what comes back — with the connection state always on screen rather than inferred from silence.',
    hotspots: [
      { anchor: 'Communication', title: 'Communication',
        body: 'Compose a message, send it, see the reply in the same log. JSON is highlighted both ways.' },
      { anchor: 'Send', title: 'Send',
        body: 'Or Ctrl+Enter. Any {{variables}} in the URL, headers or body resolve against the active environment just before the call goes out.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
    ],
  },
  {
    id: 'tour-ws-log',
    capture: 'ws-log',
    section: 'realtime',
    chapter: 'Realtime',
    title: 'The message log',
    blurb: 'Every frame with a direction, a timestamp and its payload, kept as long as the tab is open.',
    hotspots: [
      { anchor: 'Log', title: 'Log tab',
        body: 'Filterable, copyable, and each entry expands to its full payload.' },
      { anchor: 'Send', title: 'Send',
        body: 'Or Ctrl+Enter. Any {{variables}} in the URL, headers or body resolve against the active environment just before the call goes out.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
    ],
  },
  {
    id: 'tour-ws-protocols',
    capture: 'ws-protocols',
    section: 'realtime',
    chapter: 'Realtime',
    title: 'Sub-protocols and headers',
    blurb: 'The handshake is an HTTP request, so it takes headers — and a sub-protocol list if the server needs one.',
    hotspots: [
      { anchor: 'Protocols', title: 'Protocols tab',
        body: 'Sec-WebSocket-Protocol values, offered in order, plus the handshake headers.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
      { anchor: 'No Environment', title: 'Environment picker',
        body: 'The environment supplying {{variables}} right now. Going from local to staging is this dropdown rather than an edit to every request.' },
    ],
  },
  {
    id: 'tour-ws-templates',
    capture: 'ws-templates',
    section: 'realtime',
    chapter: 'Realtime',
    title: 'Message templates',
    blurb: 'The messages you send over and over, saved and one click away.',
    hotspots: [
      { anchor: 'Templates', title: 'Templates tab',
        body: 'Named payloads for a protocol you are exercising repeatedly.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
      { anchor: 'No Environment', title: 'Environment picker',
        body: 'The environment supplying {{variables}} right now. Going from local to staging is this dropdown rather than an edit to every request.' },
    ],
  },
  {
    id: 'tour-realtime-sse',
    capture: 'realtime-sse',
    section: 'realtime',
    chapter: 'Realtime',
    title: 'Server-Sent Events',
    blurb: 'A one-way stream, with each event named and timestamped as it arrives.',
    hotspots: [
      { anchor: 'SSE', title: 'SSE tab',
        body: 'Event type, id and data per row, with automatic reconnection handled as the spec describes.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
      { anchor: 'No Environment', title: 'Environment picker',
        body: 'The environment supplying {{variables}} right now. Going from local to staging is this dropdown rather than an edit to every request.' },
    ],
  },
  {
    id: 'tour-sio-communication',
    capture: 'sio-communication',
    section: 'realtime',
    chapter: 'Realtime',
    title: 'Socket.IO',
    blurb: 'Events rather than frames — emit by name with a payload, and listen for the ones coming back.',
    hotspots: [
      { anchor: 'Communication', title: 'Emit and listen',
        body: 'Named events with JSON payloads, plus acknowledgements where the server sends them.' },
      { anchor: 'Send', title: 'Send',
        body: 'Or Ctrl+Enter. Any {{variables}} in the URL, headers or body resolve against the active environment just before the call goes out.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
    ],
  },
  {
    id: 'tour-sio-log',
    capture: 'sio-log',
    section: 'realtime',
    chapter: 'Realtime',
    title: 'The Socket.IO log',
    blurb: 'Every event in and out, by name, with its payload.',
    hotspots: [
      { anchor: 'Log', title: 'Event log',
        body: 'Filter by event name to watch one conversation inside a busy socket.' },
      { anchor: 'Send', title: 'Send',
        body: 'Or Ctrl+Enter. Any {{variables}} in the URL, headers or body resolve against the active environment just before the call goes out.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
    ],
  },
  {
    id: 'tour-sio-authorization',
    capture: 'sio-authorization',
    section: 'realtime',
    chapter: 'Realtime',
    title: 'Socket.IO auth',
    blurb: 'Handshake auth, which is where Socket.IO expects a token.',
    hotspots: [
      { anchor: 'Authorization', title: 'Authorization tab',
        body: 'Sent with the handshake rather than as a header, because that is what the client library does.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
      { anchor: 'No Environment', title: 'Environment picker',
        body: 'The environment supplying {{variables}} right now. Going from local to staging is this dropdown rather than an edit to every request.' },
    ],
  },
  {
    id: 'tour-realtime-mqtt',
    capture: 'realtime-mqtt',
    section: 'realtime',
    chapter: 'Realtime',
    title: 'MQTT topics',
    blurb: 'Subscribe to topics, publish to them, and watch the traffic on both.',
    hotspots: [
      { anchor: 'MQTT', title: 'Topics',
        body: 'Wildcard subscriptions, QoS per subscription, and retained messages shown as such.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
      { anchor: 'No Environment', title: 'Environment picker',
        body: 'The environment supplying {{variables}} right now. Going from local to staging is this dropdown rather than an edit to every request.' },
    ],
  },
  {
    id: 'tour-mockserver-rest-routes',
    capture: 'mockserver-rest-routes',
    section: 'mock-server',
    chapter: 'Mock Server',
    title: 'A mock server that runs inside the editor',
    blurb: 'Define routes and responses and Daakia serves them on a real port. Useful before the backend exists, and useful when you need a failure the real one will not produce on demand.',
    hotspots: [
      { anchor: 'Routes', title: 'Routes',
        body: 'Method, path and response per row, matched the way a real router would match them.' },
      { anchor: 'Start', title: 'Start it',
        body: 'Binds a real port. Anything that can make an HTTP request can now talk to it.' },
      { anchor: 'Mock Servers', title: 'Your mocks',
        body: 'Each is a real server on a real port. Anything that can make a request can talk to it, including the rest of Daakia.' },
      { anchor: 'Not running', title: 'Server state',
        body: 'Stopped, starting or listening - and the port it holds while it is.' },
    ],
  },
  {
    id: 'tour-mockserver-rest-catalog',
    capture: 'mockserver-rest-catalog',
    section: 'mock-server',
    chapter: 'Mock Server',
    title: 'A catalog of ready-made APIs',
    blurb: 'Sample APIs to start from rather than an empty route table.',
    hotspots: [
      { anchor: 'Catalog', title: 'Catalog',
        body: 'Load a realistic API and edit it down, which is faster than building one route at a time.' },
      { anchor: 'Mock Servers', title: 'Your mocks',
        body: 'Each is a real server on a real port. Anything that can make a request can talk to it, including the rest of Daakia.' },
      { anchor: 'Routes', title: 'Routes',
        body: 'Method, path and response per row, matched the way a real router matches them.' },
      { anchor: 'Start', title: 'Start',
        body: 'Binds the port. From that moment it is a server, not a description of one.' },
    ],
  },
  {
    id: 'tour-mockserver-route-response',
    capture: 'mockserver-route-response',
    section: 'mock-server',
    chapter: 'Mock Server',
    title: 'What a route returns',
    blurb: 'Status, headers and body, with helpers for data that should look real.',
    hotspots: [
      { anchor: 'Response', title: 'Response editor',
        body: 'Template helpers generate names, ids and dates, so a list endpoint does not return the same row ten times.' },
      { anchor: 'Response Body', title: 'Response body',
        body: 'Syntax-highlighted and foldable, with a filter box for JSONPath or XPath. Right-click anything here to compare it with your clipboard.' },
      { anchor: 'Status', title: 'Status',
        body: 'The code, the time it took and the size it came to - the three numbers you check before reading anything else.' },
      { anchor: 'Mock Servers', title: 'Your mocks',
        body: 'Each is a real server on a real port. Anything that can make a request can talk to it, including the rest of Daakia.' },
    ],
  },
  {
    id: 'tour-mockserver-route-matching',
    capture: 'mockserver-route-matching',
    section: 'mock-server',
    chapter: 'Mock Server',
    title: 'Matching a request to a response',
    blurb: 'Serve a different answer depending on what was asked.',
    hotspots: [
      { anchor: 'Matching', title: 'Matching rules',
        body: 'Match on query, header or body, so one path can answer several ways.' },
      { anchor: 'Response', title: 'Response',
        body: 'What came back, in the shape the protocol describes rather than as raw text.' },
      { anchor: 'Mock Servers', title: 'Your mocks',
        body: 'Each is a real server on a real port. Anything that can make a request can talk to it, including the rest of Daakia.' },
      { anchor: 'Routes', title: 'Routes',
        body: 'Method, path and response per row, matched the way a real router matches them.' },
    ],
  },
  {
    id: 'tour-mockserver-route-sequence',
    capture: 'mockserver-route-sequence',
    section: 'mock-server',
    chapter: 'Mock Server',
    title: 'Sequences for polling clients',
    blurb: 'First call 202, second 202, third 200 — the shape a polling client needs to be tested against.',
    hotspots: [
      { anchor: 'Response Body', title: 'Response body',
        body: 'Syntax-highlighted and foldable, with a filter box for JSONPath or XPath. Right-click anything here to compare it with your clipboard.' },
      { anchor: 'Response', title: 'Response',
        body: 'What came back, in the shape the protocol describes rather than as raw text.' },
      { anchor: 'Status', title: 'Status',
        body: 'The code, the time it took and the size it came to - the three numbers you check before reading anything else.' },
      { anchor: 'Mock Servers', title: 'Your mocks',
        body: 'Each is a real server on a real port. Anything that can make a request can talk to it, including the rest of Daakia.' },
    ],
  },
  {
    id: 'tour-mockserver-route-advanced',
    capture: 'mockserver-route-advanced',
    section: 'mock-server',
    chapter: 'Mock Server',
    title: 'Delays, and other realities',
    blurb: 'Latency, jitter and conditional failure, because a backend that always answers instantly is not the one you are shipping against.',
    hotspots: [
      { anchor: 'Advanced', title: 'Advanced',
        body: 'Fixed or random delay per route, and the failure modes worth rehearsing.' },
      { anchor: 'Response', title: 'Response',
        body: 'What came back, in the shape the protocol describes rather than as raw text.' },
      { anchor: 'Mock Servers', title: 'Your mocks',
        body: 'Each is a real server on a real port. Anything that can make a request can talk to it, including the rest of Daakia.' },
      { anchor: 'Routes', title: 'Routes',
        body: 'Method, path and response per row, matched the way a real router matches them.' },
    ],
  },
  {
    id: 'tour-mockserver-chaos',
    capture: 'mockserver-chaos',
    section: 'mock-server',
    chapter: 'Mock Server',
    title: 'Chaos',
    blurb: 'Break things on purpose: drop connections, corrupt payloads, time out.',
    hotspots: [
      { anchor: 'Chaos', title: 'Chaos',
        body: 'Applied across the server rather than per route, so you are testing the client rather than one endpoint.' },
      { anchor: 'Mock Servers', title: 'Your mocks',
        body: 'Each is a real server on a real port. Anything that can make a request can talk to it, including the rest of Daakia.' },
      { anchor: 'Routes', title: 'Routes',
        body: 'Method, path and response per row, matched the way a real router matches them.' },
      { anchor: 'Start', title: 'Start',
        body: 'Binds the port. From that moment it is a server, not a description of one.' },
    ],
  },
  {
    id: 'tour-mockserver-statemachine',
    capture: 'mockserver-statemachine',
    section: 'mock-server',
    chapter: 'Mock Server',
    title: 'A mock with a memory',
    blurb: 'A state machine behind the routes, so a sequence of calls behaves like a workflow instead of independent requests.',
    hotspots: [
      { anchor: 'State Machine', title: 'State machine',
        body: 'States, transitions and the responses each state gives — a cart that fills, checks out and empties.' },
      { anchor: 'Response Body', title: 'Response body',
        body: 'Syntax-highlighted and foldable, with a filter box for JSONPath or XPath. Right-click anything here to compare it with your clipboard.' },
      { anchor: 'Response', title: 'Response',
        body: 'What came back, in the shape the protocol describes rather than as raw text.' },
      { anchor: 'Status', title: 'Status',
        body: 'The code, the time it took and the size it came to - the three numbers you check before reading anything else.' },
    ],
  },
  {
    id: 'tour-mockserver-flow',
    capture: 'mockserver-flow',
    section: 'mock-server',
    chapter: 'Mock Server',
    title: 'The flow, drawn',
    blurb: 'The same workflow as a diagram, which is easier to argue about than a table.',
    hotspots: [
      { anchor: 'Start', title: 'Start',
        body: 'Binds the port. From that moment it is a server, not a description of one.' },
      { anchor: 'Advanced', title: 'Advanced',
        body: 'Latency and jitter per route. A backend that always answers instantly is not the one you are shipping against.' },
      { anchor: 'State Machine', title: 'State machine',
        body: 'States, transitions and the response each state gives, so a run of calls behaves like a workflow rather than independent requests.' },
    ],
  },
  {
    id: 'tour-mockserver-traffic',
    capture: 'mockserver-traffic',
    section: 'mock-server',
    chapter: 'Mock Server',
    title: 'Traffic through the mock',
    blurb: 'Every request the mock served, with what it answered.',
    hotspots: [
      { anchor: 'Traffic', title: 'Traffic log',
        body: 'What the client actually sent — often the fastest way to find out why it is not matching your route.' },
      { anchor: 'Mock Servers', title: 'Your mocks',
        body: 'Each is a real server on a real port. Anything that can make a request can talk to it, including the rest of Daakia.' },
      { anchor: 'Routes', title: 'Routes',
        body: 'Method, path and response per row, matched the way a real router matches them.' },
      { anchor: 'Catalog', title: 'Catalog',
        body: 'Ready-made sample APIs to start from and edit down, which beats building one route at a time.' },
    ],
  },
  {
    id: 'tour-mockserver-graphql-schema',
    capture: 'mockserver-graphql-schema',
    section: 'mock-server',
    chapter: 'Mock Server',
    title: 'A GraphQL mock',
    blurb: 'An SDL schema served with generated resolvers.',
    hotspots: [
      { anchor: 'Schema', title: 'Schema',
        body: 'Types in, mock data out, without writing a resolver for each field.' },
      { anchor: 'Response', title: 'Response',
        body: 'What came back, in the shape the protocol describes rather than as raw text.' },
      { anchor: 'Query', title: 'Query editor',
        body: 'Completion comes from the introspected schema, so field names come from the server rather than from memory.' },
      { anchor: 'Mock Servers', title: 'Your mocks',
        body: 'Each is a real server on a real port. Anything that can make a request can talk to it, including the rest of Daakia.' },
    ],
  },
  {
    id: 'tour-mockserver-soap-services',
    capture: 'mockserver-soap-services',
    section: 'mock-server',
    chapter: 'Mock Server',
    title: 'A SOAP mock',
    blurb: 'Operations served from a WSDL, envelopes and all.',
    hotspots: [
      { anchor: 'Services', title: 'Services',
        body: 'Each operation with the envelope it returns.' },
      { anchor: 'Response', title: 'Response',
        body: 'What came back, in the shape the protocol describes rather than as raw text.' },
      { anchor: 'WSDL', title: 'WSDL',
        body: 'Point at the document and Daakia lists the services, ports and operations it declares - no guessing at SOAPAction strings.' },
      { anchor: 'Mock Servers', title: 'Your mocks',
        body: 'Each is a real server on a real port. Anything that can make a request can talk to it, including the rest of Daakia.' },
    ],
  },
  {
    id: 'tour-mockserver-wsdl',
    capture: 'mockserver-wsdl',
    section: 'mock-server',
    chapter: 'Mock Server',
    title: 'The WSDL the mock publishes',
    blurb: 'Generated and served, so a real SOAP client can consume it.',
    hotspots: [
      { anchor: 'WSDL', title: 'WSDL',
        body: 'A document a client can point at, rather than a description of one.' },
      { anchor: 'Mock Servers', title: 'Your mocks',
        body: 'Each is a real server on a real port. Anything that can make a request can talk to it, including the rest of Daakia.' },
      { anchor: 'Start', title: 'Start',
        body: 'Binds the port. From that moment it is a server, not a description of one.' },
      { anchor: 'Not running', title: 'Server state',
        body: 'Stopped, starting or listening - and the port it holds while it is.' },
    ],
  },
  {
    id: 'tour-mockserver-grpc-routes',
    capture: 'mockserver-grpc-routes',
    section: 'mock-server',
    chapter: 'Mock Server',
    title: 'A gRPC mock',
    blurb: 'Services and methods from a proto, answering with messages of the right type.',
    hotspots: [
      { anchor: 'Mock Servers', title: 'Your mocks',
        body: 'Each is a real server on a real port. Anything that can make a request can talk to it, including the rest of Daakia.' },
      { anchor: 'Start', title: 'Start',
        body: 'Binds the port. From that moment it is a server, not a description of one.' },
      { anchor: 'Not running', title: 'Server state',
        body: 'Stopped, starting or listening - and the port it holds while it is.' },
      { anchor: 'Catalog', title: 'Catalog',
        body: 'Ready-made sample APIs to start from and edit down, which beats building one route at a time.' },
    ],
  },
  {
    id: 'tour-mockserver-ws-handlers',
    capture: 'mockserver-ws-handlers',
    section: 'mock-server',
    chapter: 'Mock Server',
    title: 'A WebSocket mock',
    blurb: 'Reply to a message with a message — trigger and response.',
    hotspots: [
      { anchor: 'Handlers', title: 'Handlers',
        body: 'Pattern in, payload out, which is enough to drive most clients.' },
      { anchor: 'Mock Servers', title: 'Your mocks',
        body: 'Each is a real server on a real port. Anything that can make a request can talk to it, including the rest of Daakia.' },
      { anchor: 'Start', title: 'Start',
        body: 'Binds the port. From that moment it is a server, not a description of one.' },
      { anchor: 'Not running', title: 'Server state',
        body: 'Stopped, starting or listening - and the port it holds while it is.' },
    ],
  },
  {
    id: 'tour-mockserver-sio-messages',
    capture: 'mockserver-sio-messages',
    section: 'mock-server',
    chapter: 'Mock Server',
    title: 'A Socket.IO mock',
    blurb: 'Named events in both directions, so a client that speaks Socket.IO rather than raw frames has something to speak to.',
    hotspots: [
      { anchor: 'Messages', title: 'Events',
        body: 'Client-to-server and server-to-client, by event name.' },
      { anchor: 'Mock Servers', title: 'Your mocks',
        body: 'Each is a real server on a real port. Anything that can make a request can talk to it, including the rest of Daakia.' },
      { anchor: 'Start', title: 'Start',
        body: 'Binds the port. From that moment it is a server, not a description of one.' },
      { anchor: 'Not running', title: 'Server state',
        body: 'Stopped, starting or listening - and the port it holds while it is.' },
    ],
  },
  {
    id: 'tour-mockserver-sse-events',
    capture: 'mockserver-sse-events',
    section: 'mock-server',
    chapter: 'Mock Server',
    title: 'An SSE mock',
    blurb: 'A scripted event stream on an interval you choose, which is enough to exercise a client that has to reconnect.',
    hotspots: [
      { anchor: 'Events', title: 'Events',
        body: 'Event type, data and cadence — enough to exercise a reconnecting client.' },
      { anchor: 'Mock Servers', title: 'Your mocks',
        body: 'Each is a real server on a real port. Anything that can make a request can talk to it, including the rest of Daakia.' },
      { anchor: 'Start', title: 'Start',
        body: 'Binds the port. From that moment it is a server, not a description of one.' },
      { anchor: 'Not running', title: 'Server state',
        body: 'Stopped, starting or listening - and the port it holds while it is.' },
    ],
  },
  {
    id: 'tour-mockserver-mqtt-topics',
    capture: 'mockserver-mqtt-topics',
    section: 'mock-server',
    chapter: 'Mock Server',
    title: 'An MQTT mock',
    blurb: 'Topics that publish on a schedule, which is the only way to give a subscriber something to receive before the real broker exists.',
    hotspots: [
      { anchor: 'Topics', title: 'Topics',
        body: 'Topic, payload and interval, for a subscriber that needs something to receive.' },
      { anchor: 'Mock Servers', title: 'Your mocks',
        body: 'Each is a real server on a real port. Anything that can make a request can talk to it, including the rest of Daakia.' },
      { anchor: 'Start', title: 'Start',
        body: 'Binds the port. From that moment it is a server, not a description of one.' },
      { anchor: 'Not running', title: 'Server state',
        body: 'Stopped, starting or listening - and the port it holds while it is.' },
    ],
  },
  {
    id: 'tour-mockserver-import',
    capture: 'mockserver-import',
    section: 'mock-server',
    chapter: 'Mock Server',
    title: 'Import a spec',
    blurb: 'OpenAPI, Postman, WireMock — turned into routes rather than read by hand.',
    hotspots: [
      { anchor: 'Import', title: 'Import',
        body: 'A spec becomes a working mock in one step.' },
      { anchor: 'Mock Servers', title: 'Your mocks',
        body: 'Each is a real server on a real port. Anything that can make a request can talk to it, including the rest of Daakia.' },
      { anchor: 'Routes', title: 'Routes',
        body: 'Method, path and response per row, matched the way a real router matches them.' },
      { anchor: 'Start', title: 'Start',
        body: 'Binds the port. From that moment it is a server, not a description of one.' },
    ],
  },
  {
    id: 'tour-mockserver-export',
    capture: 'mockserver-export',
    section: 'mock-server',
    chapter: 'Mock Server',
    title: 'Export what you built',
    blurb: 'Take the mock elsewhere, or check it into the repo.',
    hotspots: [
      { anchor: 'Export', title: 'Export',
        body: 'A standalone server, or a config another tool understands.' },
      { anchor: 'Mock Servers', title: 'Your mocks',
        body: 'Each is a real server on a real port. Anything that can make a request can talk to it, including the rest of Daakia.' },
      { anchor: 'Routes', title: 'Routes',
        body: 'Method, path and response per row, matched the way a real router matches them.' },
      { anchor: 'Start', title: 'Start',
        body: 'Binds the port. From that moment it is a server, not a description of one.' },
    ],
  },
  {
    id: 'tour-platform-sidebar-collections',
    capture: 'platform-sidebar-collections',
    section: 'platform',
    chapter: 'Collections & Environments',
    title: 'Collections keep requests where you left them',
    blurb: 'A collection is a folder of saved requests with its own variables, inherited headers and auth. A saved request keeps its last response too, so reopening one shows what it returned.',
    hotspots: [
      { anchor: 'Collections', title: 'Collections',
        body: 'Folders inside folders, dragged to reorder, starred to float to the top.' },
      { anchor: 'Send', title: 'Send',
        body: 'Or Ctrl+Enter. Any {{variables}} in the URL, headers or body resolve against the active environment just before the call goes out.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
    ],
  },
  {
    id: 'tour-platform-sidebar-history',
    capture: 'platform-sidebar-history',
    section: 'platform',
    chapter: 'Collections & Environments',
    title: 'Every request you have sent',
    blurb: 'Automatic, searchable, and replayable — including the ones you never got round to saving.',
    hotspots: [
      { anchor: 'History', title: 'History',
        body: 'Grouped by day, filterable, and one click to replay with the exact same body and headers.' },
      { anchor: 'Send', title: 'Send',
        body: 'Or Ctrl+Enter. Any {{variables}} in the URL, headers or body resolve against the active environment just before the call goes out.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
    ],
  },
  {
    id: 'tour-platform-sidebar-environments',
    capture: 'platform-sidebar-environments',
    section: 'platform',
    chapter: 'Collections & Environments',
    title: 'Environments swap the values, not the requests',
    blurb: '{{baseUrl}} resolves against whichever environment is active, so moving from local to staging is a dropdown rather than an edit.',
    hotspots: [
      { anchor: 'Environments', title: 'Environments',
        body: 'Each variable has an initial value to share and a current value for this machine — which is where a token belongs.' },
      { anchor: 'Send', title: 'Send',
        body: 'Or Ctrl+Enter. Any {{variables}} in the URL, headers or body resolve against the active environment just before the call goes out.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
    ],
  },
  {
    id: 'tour-platform-devtools-console',
    capture: 'platform-devtools-console',
    section: 'platform',
    chapter: 'DevTools & AI',
    title: 'A console for the app itself',
    blurb: 'Script output, protocol events and settings changes, in one place.',
    hotspots: [
      { anchor: 'Console', title: 'Console',
        body: 'Colour-coded by level, with objects expandable rather than stringified.' },
      { anchor: 'Send', title: 'Send',
        body: 'Or Ctrl+Enter. Any {{variables}} in the URL, headers or body resolve against the active environment just before the call goes out.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
    ],
  },
  {
    id: 'tour-platform-devtools-network',
    capture: 'platform-devtools-network',
    section: 'platform',
    chapter: 'DevTools & AI',
    title: 'Every call, listed',
    blurb: 'Method, status, URL, time and size for everything the app has sent.',
    hotspots: [
      { anchor: 'Network', title: 'Network',
        body: 'Click a row for the full request and response, the way a browser devtools panel works.' },
      { anchor: 'Send', title: 'Send',
        body: 'Or Ctrl+Enter. Any {{variables}} in the URL, headers or body resolve against the active environment just before the call goes out.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
    ],
  },
  {
    id: 'tour-platform-command-palette',
    capture: 'platform-command-palette',
    section: 'platform',
    chapter: 'DevTools & AI',
    title: 'Everything by keyboard',
    blurb: 'Ctrl+K reaches any protocol, request, collection or setting without touching the mouse.',
    hotspots: [
      { anchor: 'Send', title: 'Send',
        body: 'Or Ctrl+Enter. Any {{variables}} in the URL, headers or body resolve against the active environment just before the call goes out.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Untitled Request', title: 'The tab',
        body: 'Every open request is a tab, colour-dotted by protocol. An orange dot means unsaved; right-click for rename, duplicate or close others.' },
      { anchor: 'Collections', title: 'Collections',
        body: 'Saved requests in folders, with variables, headers and auth that everything inside inherits unless it overrides them.' },
    ],
  },
  {
    id: 'tour-settings-ai-features',
    capture: 'settings-ai-features',
    section: 'platform',
    chapter: 'DevTools & AI',
    title: 'Every AI feature, individually switchable',
    blurb: 'Around a hundred AI actions, each with a name, a screen, a switch and a line in the audit when it runs.',
    hotspots: [
      { anchor: 'AI Features', title: 'AI Features',
        body: 'Grouped by the screen the feature lives on. Turning one off stops the call being made at all — not just the button being hidden.' },
      { anchor: 'Collections', title: 'Collections',
        body: 'Saved requests in folders, with variables, headers and auth that everything inside inherits unless it overrides them.' },
      { anchor: 'Settings', title: 'Settings',
        body: 'Per-request overrides: redirects, TLS verification, timeouts and tags - the global defaults apply until one of these says otherwise.' },
      { anchor: 'Advanced', title: 'Advanced',
        body: 'Latency and jitter per route. A backend that always answers instantly is not the one you are shipping against.' },
    ],
  },
  {
    id: 'tour-settings-prompt-library',
    capture: 'settings-prompt-library',
    section: 'platform',
    chapter: 'DevTools & AI',
    title: 'The prompts, readable and editable',
    blurb: 'Every AI feature sends a prompt from here. Nothing is sent that you cannot read first, and every one can be rewritten.',
    hotspots: [
      { anchor: 'Prompt Library', title: 'Prompt Library',
        body: 'The user half and the system half of each prompt, with the variables each one takes.' },
      { anchor: 'Settings', title: 'Settings',
        body: 'Per-request overrides: redirects, TLS verification, timeouts and tags - the global defaults apply until one of these says otherwise.' },
      { anchor: 'Advanced', title: 'Advanced',
        body: 'Latency and jitter per route. A backend that always answers instantly is not the one you are shipping against.' },
      { anchor: 'Record Baseline', title: 'Record a baseline',
        body: 'Capture what the mock returns now, so a later change shows up as a difference rather than a surprise.' },
    ],
  },
  {
    id: 'tour-settings-ai-audit',
    capture: 'settings-ai-audit',
    section: 'platform',
    chapter: 'DevTools & AI',
    title: 'What was sent, and from where',
    blurb: 'Every AI call by feature name and the screen it came from, with the model, the duration and the full exchange kept.',
    hotspots: [
      { anchor: 'AI Audit', title: 'AI Audit',
        body: 'A failure keeps its error here rather than vanishing with the toast.' },
      { anchor: 'Settings', title: 'Settings',
        body: 'Per-request overrides: redirects, TLS verification, timeouts and tags - the global defaults apply until one of these says otherwise.' },
      { anchor: 'Advanced', title: 'Advanced',
        body: 'Latency and jitter per route. A backend that always answers instantly is not the one you are shipping against.' },
      { anchor: 'Developer Tools', title: 'Developer tools',
        body: 'The audit log, the database explorer and a snapshot worth attaching to a bug report.' },
    ],
  },
  {
    id: 'tour-settings-llm-provider',
    capture: 'settings-llm-provider',
    section: 'platform',
    chapter: 'DevTools & AI',
    title: 'Which model answers',
    blurb: 'Copilot, OpenAI, Anthropic, Ollama and the rest — keys in the OS keychain, never in the workspace.',
    hotspots: [
      { anchor: 'LLM Provider', title: 'Providers',
        body: 'Pick a default, or set one per tab. Keys live in the keychain, not in a settings file.' },
      { anchor: 'Settings', title: 'Settings',
        body: 'Per-request overrides: redirects, TLS verification, timeouts and tags - the global defaults apply until one of these says otherwise.' },
      { anchor: 'Advanced', title: 'Advanced',
        body: 'Latency and jitter per route. A backend that always answers instantly is not the one you are shipping against.' },
      { anchor: 'Developer Tools', title: 'Developer tools',
        body: 'The audit log, the database explorer and a snapshot worth attaching to a bug report.' },
    ],
  },
  {
    id: 'tour-settings-general',
    capture: 'settings-general',
    section: 'platform',
    chapter: 'Settings',
    title: 'Settings',
    blurb: 'Redirects, TLS verification, timeouts, history limits and where the database lives.',
    hotspots: [
      { anchor: 'General', title: 'General',
        body: 'The switches that apply to every request unless a request overrides them.' },
      { anchor: 'Settings', title: 'Settings',
        body: 'Per-request overrides: redirects, TLS verification, timeouts and tags - the global defaults apply until one of these says otherwise.' },
      { anchor: 'Advanced', title: 'Advanced',
        body: 'Latency and jitter per route. A backend that always answers instantly is not the one you are shipping against.' },
      { anchor: 'Developer Tools', title: 'Developer tools',
        body: 'The audit log, the database explorer and a snapshot worth attaching to a bug report.' },
    ],
  },
  {
    id: 'tour-settings-theme',
    capture: 'settings-theme',
    section: 'platform',
    chapter: 'Settings',
    title: 'Theme',
    blurb: 'Light and dark, following VS Code or pinned.',
    hotspots: [
      { anchor: 'Theme', title: 'Theme',
        body: 'Every colour in the app is a token, so a theme change reaches all of it.' },
      { anchor: 'Settings', title: 'Settings',
        body: 'Per-request overrides: redirects, TLS verification, timeouts and tags - the global defaults apply until one of these says otherwise.' },
      { anchor: 'Advanced', title: 'Advanced',
        body: 'Latency and jitter per route. A backend that always answers instantly is not the one you are shipping against.' },
      { anchor: 'Developer Tools', title: 'Developer tools',
        body: 'The audit log, the database explorer and a snapshot worth attaching to a bug report.' },
    ],
  },
  {
    id: 'tour-settings-power-features',
    capture: 'settings-power-features',
    section: 'platform',
    chapter: 'Settings',
    title: 'Power features',
    blurb: 'The tools that do not belong to one protocol: load testing, bulk checks, a proxy, a diff.',
    hotspots: [
      { anchor: 'Power Features', title: 'Power Features',
        body: 'Each opens its own panel. The load tester and bulk checker send real traffic and report what actually came back.' },
      { anchor: 'Settings', title: 'Settings',
        body: 'Per-request overrides: redirects, TLS verification, timeouts and tags - the global defaults apply until one of these says otherwise.' },
      { anchor: 'Advanced', title: 'Advanced',
        body: 'Latency and jitter per route. A backend that always answers instantly is not the one you are shipping against.' },
      { anchor: 'Developer Tools', title: 'Developer tools',
        body: 'The audit log, the database explorer and a snapshot worth attaching to a bug report.' },
    ],
  },
  {
    id: 'tour-settings-developer-tools',
    capture: 'settings-developer-tools',
    section: 'platform',
    chapter: 'Settings',
    title: 'Developer tools',
    blurb: 'The audit log, the database explorer and a snapshot for reporting a bug.',
    hotspots: [
      { anchor: 'Developer Tools', title: 'Developer Tools',
        body: 'Every UI event you have opted into, with the module and action that produced it.' },
      { anchor: 'Settings', title: 'Settings',
        body: 'Per-request overrides: redirects, TLS verification, timeouts and tags - the global defaults apply until one of these says otherwise.' },
      { anchor: 'Advanced', title: 'Advanced',
        body: 'Latency and jitter per route. A backend that always answers instantly is not the one you are shipping against.' },
      { anchor: 'Power Features', title: 'Power features',
        body: 'The tools that belong to no single protocol: load testing, bulk URL checks, a forward proxy and a diff.' },
    ],
  },
  {
    id: 'tour-settings-mock-server',
    capture: 'settings-mock-server',
    section: 'platform',
    chapter: 'Settings',
    title: 'Mock server settings',
    blurb: 'Ports, persistence and what happens on restart.',
    hotspots: [
      { anchor: 'Mock Server', title: 'Mock Server',
        body: 'Where mocks live and which ones come back when the editor reopens.' },
      { anchor: 'Save', title: 'Save',
        body: 'Saves the request into a collection - and, since responses are stored with it, reopening it later shows the answer it last gave.' },
      { anchor: 'Settings', title: 'Settings',
        body: 'Per-request overrides: redirects, TLS verification, timeouts and tags - the global defaults apply until one of these says otherwise.' },
      { anchor: 'Advanced', title: 'Advanced',
        body: 'Latency and jitter per route. A backend that always answers instantly is not the one you are shipping against.' },
    ],
  },
  {
    id: 'tour-dk8s-pods',
    capture: 'dk8s-pods',
    section: 'dk8s',
    chapter: 'dk8s',
    title: 'A cluster, from inside the editor',
    blurb: 'dk8s points Daakia at Kubernetes: the pods it is watching, their health, and everything a pod can tell you — logs, heap, threads, a shell.',
    hotspots: [
      { anchor: 'docker-desktop', title: 'Context and namespace',
        body: 'Watch several at once. dk8s asks the cluster what you are allowed to do before offering it, so a forbidden action is a disabled button with a reason.' },
      { anchor: 'watching', title: 'Watch state',
        body: 'How many pods, how many ready, how many failing — live, rather than on a refresh button.' },
      { anchor: 'CrashLoopBackOff', title: 'A failing pod',
        body: 'Styled so it is findable across the room, with its restart count and how long ago the last one was.' },
      { anchor: 'Quick Search', title: 'Command palette',
        body: 'Ctrl+K, then fuzzy search over tabs, collections, history, settings and every command.' },
    ],
  },
  {
    id: 'tour-dk8s-pods-table',
    capture: 'dk8s-pods-table',
    section: 'dk8s',
    chapter: 'dk8s',
    title: 'The same pods, dense',
    blurb: 'Cards for a small namespace, a table for a large one.',
    hotspots: [
      { anchor: 'table', title: 'Table view',
        body: 'Sortable columns, one row per pod, the same actions on each.' },
      { anchor: 'Status', title: 'Status',
        body: 'The code, the time it took and the size it came to - the three numbers you check before reading anything else.' },
      { anchor: 'Quick Search', title: 'Command palette',
        body: 'Ctrl+K, then fuzzy search over tabs, collections, history, settings and every command.' },
      { anchor: 'Pods', title: 'Pods',
        body: 'Everything dk8s is watching, live - how many are ready and how many are failing, without a refresh button.' },
    ],
  },
  {
    id: 'tour-dk8s-overview',
    capture: 'dk8s-overview',
    section: 'dk8s',
    chapter: 'dk8s',
    title: 'One pod at a glance',
    blurb: 'Containers, workload, image, node, age, restarts — and the actions the cluster will actually permit.',
    hotspots: [
      { anchor: 'Overview', title: 'Overview tab',
        body: 'What the pod is and what it is doing, before you go looking at its logs.' },
      { anchor: 'Quick Search', title: 'Command palette',
        body: 'Ctrl+K, then fuzzy search over tabs, collections, history, settings and every command.' },
      { anchor: 'Pods', title: 'Pods',
        body: 'Everything dk8s is watching, live - how many are ready and how many are failing, without a refresh button.' },
      { anchor: 'watching', title: 'Watch state',
        body: 'A live watch rather than polling, so a pod that starts failing shows it at the moment it does.' },
    ],
  },
  {
    id: 'tour-dk8s-logs',
    capture: 'dk8s-logs',
    section: 'dk8s',
    chapter: 'dk8s',
    title: 'Logs you can narrow instead of scroll',
    blurb: 'A live stream with levels, and facets built from the fields your log format actually names — so "only this thread" is a click rather than a grep.',
    hotspots: [
      { anchor: 'Logs', title: 'Logs tab',
        body: 'Streaming, with tail depth, a since-window and wrap all on the same row.' },
      { anchor: 'error', title: 'Levels',
        body: 'Turning one off never moves the rest of the panel — the filter strip sits beside the list for exactly that reason.' },
      { anchor: 'Quick Search', title: 'Command palette',
        body: 'Ctrl+K, then fuzzy search over tabs, collections, history, settings and every command.' },
      { anchor: 'Pods', title: 'Pods',
        body: 'Everything dk8s is watching, live - how many are ready and how many are failing, without a refresh button.' },
    ],
  },
  {
    id: 'tour-dk8s-logs-filtered',
    capture: 'dk8s-logs-filtered',
    section: 'dk8s',
    chapter: 'dk8s',
    title: 'The same stream, narrowed',
    blurb: 'Levels and field facets combine, and the count beside each is the count in the buffer.',
    hotspots: [
      { anchor: 'error', title: 'A level filter',
        body: 'Errors and warnings only. Never guessed: a facet appears only where a field was really parsed.' },
      { anchor: 'Quick Search', title: 'Command palette',
        body: 'Ctrl+K, then fuzzy search over tabs, collections, history, settings and every command.' },
      { anchor: 'Pods', title: 'Pods',
        body: 'Everything dk8s is watching, live - how many are ready and how many are failing, without a refresh button.' },
      { anchor: 'docker-desktop', title: 'Context',
        body: 'Which cluster. dk8s asks it what you may do before offering it, so a forbidden action is a disabled button with a reason.' },
    ],
  },
  {
    id: 'tour-dk8s-terminal',
    capture: 'dk8s-terminal',
    section: 'dk8s',
    chapter: 'dk8s',
    title: 'A shell in the container',
    blurb: 'Over kubectl exec, in the same terminal surface as the rest of Daakia.',
    hotspots: [
      { anchor: 'Terminal', title: 'Terminal tab',
        body: 'The container it is attached to is shown as a chip, because a shell in the wrong container is a bad afternoon.' },
      { anchor: 'Quick Search', title: 'Command palette',
        body: 'Ctrl+K, then fuzzy search over tabs, collections, history, settings and every command.' },
      { anchor: 'Pods', title: 'Pods',
        body: 'Everything dk8s is watching, live - how many are ready and how many are failing, without a refresh button.' },
      { anchor: 'docker-desktop', title: 'Context',
        body: 'Which cluster. dk8s asks it what you may do before offering it, so a forbidden action is a disabled button with a reason.' },
    ],
  },
  {
    id: 'tour-dk8s-explorer',
    capture: 'dk8s-explorer',
    section: 'dk8s',
    chapter: 'dk8s',
    title: 'The container filesystem',
    blurb: 'Browsable, previewable, and the way a dump gets from a pod into the analyzers.',
    hotspots: [
      { anchor: 'Explorer', title: 'Explorer tab',
        body: 'Walk the tree, preview a file, or pull it down as an artifact.' },
      { anchor: 'Quick Search', title: 'Command palette',
        body: 'Ctrl+K, then fuzzy search over tabs, collections, history, settings and every command.' },
      { anchor: 'Pods', title: 'Pods',
        body: 'Everything dk8s is watching, live - how many are ready and how many are failing, without a refresh button.' },
      { anchor: 'docker-desktop', title: 'Context',
        body: 'Which cluster. dk8s asks it what you may do before offering it, so a forbidden action is a disabled button with a reason.' },
    ],
  },
  {
    id: 'tour-dk8s-doctor',
    capture: 'dk8s-doctor',
    section: 'dk8s',
    chapter: 'dk8s',
    title: 'Take the dump, open the analyzer',
    blurb: 'Heap dumps, thread dumps and flight recordings collected straight from a running container — no kubectl cp round trip.',
    hotspots: [
      { anchor: 'Doctor', title: 'Doctor tab',
        body: 'The runtime dk8s detected and the tools it found. Anything missing is greyed out with the reason.' },
      { anchor: 'Collect', title: 'Collect',
        body: 'Each collection says its cost up front — a heap dump stops the JVM — because that matters on something serving traffic.' },
      { anchor: 'Quick Search', title: 'Command palette',
        body: 'Ctrl+K, then fuzzy search over tabs, collections, history, settings and every command.' },
      { anchor: 'Pods', title: 'Pods',
        body: 'Everything dk8s is watching, live - how many are ready and how many are failing, without a refresh button.' },
    ],
  },
  {
    id: 'tour-dk8s-artifacts',
    capture: 'dk8s-artifacts',
    section: 'dk8s',
    chapter: 'dk8s',
    title: 'Everything collected so far',
    blurb: 'Dumps and recordings with the pod and moment each came from, so one is still identifiable a week later.',
    hotspots: [
      { anchor: 'Artifacts', title: 'Artifacts',
        body: 'Open one and it lands in the analyzer built for it.' },
      { anchor: 'Pods', title: 'Pods',
        body: 'Everything dk8s is watching, live - how many are ready and how many are failing, without a refresh button.' },
      { anchor: 'Overview', title: 'Overview',
        body: 'Containers, workload, image, node, age and restarts - what the pod is, before you go into its logs.' },
      { anchor: 'Logs', title: 'Logs',
        body: 'A live stream with levels and facets built from fields your format actually names, so "only this thread" is a click rather than a grep.' },
    ],
  },
];

/** The chapters, in the order the tour walks them. */
export function tourChapters(): { chapter: string; stops: TourStop[] }[] {
  const out: { chapter: string; stops: TourStop[] }[] = [];
  for (const stop of TOUR_STOPS) {
    const last = out[out.length - 1];
    if (last && last.chapter === stop.chapter) last.stops.push(stop);
    else out.push({ chapter: stop.chapter, stops: [stop] });
  }
  return out;
}
