/** Content type → bodyMode mapping */
export const CONTENT_TYPE_MODE: Record<string, string> = {
  'none': 'none',
  'application/json': 'json',
  'application/ld+json': 'json',
  'application/hal+json': 'json',
  'application/vnd.api+json': 'json',
  'application/xml': 'raw',
  'text/xml': 'raw',
  'application/soap+xml': 'raw',
  'application/x-www-form-urlencoded': 'x-www-form-urlencoded',
  'multipart/form-data': 'form-data',
  'application/octet-stream': 'binary',
  'text/html': 'raw',
  'text/plain': 'raw',
  'text/css': 'raw',
  'text/csv': 'raw',
  'text/markdown': 'raw',
  'application/javascript': 'raw',
  'application/graphql': 'raw',
  'application/yaml': 'raw',
  'application/msgpack': 'binary',
};

/** Content type → Monaco editor language */
export const CONTENT_TYPE_LANG: Record<string, string> = {
  'application/json': 'json',
  'application/ld+json': 'json',
  'application/hal+json': 'json',
  'application/vnd.api+json': 'json',
  'application/xml': 'xml',
  'text/xml': 'xml',
  'application/soap+xml': 'xml',
  'text/html': 'html',
  'text/plain': 'plaintext',
  'text/css': 'css',
  'text/csv': 'plaintext',
  'text/markdown': 'markdown',
  'application/javascript': 'javascript',
  'application/graphql': 'graphql',
  'application/yaml': 'yaml',
};

/** Placeholder text shown in the editor when the body is empty */
export const CONTENT_TYPE_PLACEHOLDER: Record<string, string> = {
  'application/json': '{\n  "key": "value"\n}',
  'application/ld+json': '{\n  "@context": "https://schema.org",\n  "@type": "Thing",\n  "name": "value"\n}',
  'application/hal+json': '{\n  "_links": {\n    "self": { "href": "/resource/1" }\n  },\n  "key": "value"\n}',
  'application/vnd.api+json': '{\n  "data": {\n    "type": "articles",\n    "id": "1",\n    "attributes": {\n      "title": "value"\n    }\n  }\n}',
  'application/xml': '<?xml version="1.0" encoding="UTF-8"?>\n<root>\n  <element>value</element>\n</root>',
  'text/xml': '<root>\n  <element>value</element>\n</root>',
  'application/soap+xml': '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">\n  <soapenv:Header/>\n  <soapenv:Body>\n    <!-- Your operation here -->\n  </soapenv:Body>\n</soapenv:Envelope>',
  'text/html': '<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <title>Document</title>\n</head>\n<body>\n  \n</body>\n</html>',
  'text/plain': 'Plain text content here',
  'text/css': '/* CSS Styles */\nbody {\n  margin: 0;\n  padding: 0;\n}',
  'text/csv': 'column1,column2,column3\nvalue1,value2,value3',
  'text/markdown': '# Title\n\n> Blockquote\n\nContent here',
  'application/javascript': '// JavaScript code\nconst data = {};\nconsole.log(data);',
  'application/graphql': '{\n  # Your GraphQL query\n  query {\n    field\n  }\n}',
  'application/yaml': '# YAML content\nkey: value\nlist:\n  - item1\n  - item2',
};

/** Grouped content type options for the SelectInputView dropdown */
export const CONTENT_TYPE_OPTIONS = [
  { value: 'none', label: 'None', isHeader: false },
  { value: '_h_json', label: 'JSON', isHeader: true },
  { value: 'application/json', label: 'application/json', isHeader: false },
  { value: 'application/ld+json', label: 'application/ld+json', isHeader: false },
  { value: 'application/hal+json', label: 'application/hal+json', isHeader: false },
  { value: 'application/vnd.api+json', label: 'application/vnd.api+json', isHeader: false },
  { value: '_h_xml', label: 'XML', isHeader: true },
  { value: 'application/xml', label: 'application/xml', isHeader: false },
  { value: 'text/xml', label: 'text/xml', isHeader: false },
  { value: 'application/soap+xml', label: 'application/soap+xml', isHeader: false },
  { value: '_h_text', label: 'Text', isHeader: true },
  { value: 'text/plain', label: 'text/plain', isHeader: false },
  { value: 'text/html', label: 'text/html', isHeader: false },
  { value: 'text/css', label: 'text/css', isHeader: false },
  { value: 'text/csv', label: 'text/csv', isHeader: false },
  { value: 'text/markdown', label: 'text/markdown', isHeader: false },
  { value: '_h_code', label: 'Code', isHeader: true },
  { value: 'application/javascript', label: 'application/javascript', isHeader: false },
  { value: 'application/graphql', label: 'application/graphql', isHeader: false },
  { value: 'application/yaml', label: 'application/yaml', isHeader: false },
  { value: '_h_structured', label: 'Structured', isHeader: true },
  { value: 'application/x-www-form-urlencoded', label: 'application/x-www-form-urlencoded', isHeader: false },
  { value: 'multipart/form-data', label: 'multipart/form-data', isHeader: false },
  { value: '_h_binary', label: 'Binary', isHeader: true },
  { value: 'application/octet-stream', label: 'application/octet-stream', isHeader: false },
  { value: 'application/msgpack', label: 'application/msgpack', isHeader: false },
];
