/**
 * CookieManager — view/edit/delete all stored cookies across domains, import/export.
 * Feature 6B.13 — Cookie manager
 */
import { useState, useEffect } from 'react';
import { createPortal } from 'react-dom';
import { CloseIcon, TrashIcon, PlusIcon, CopyIcon } from '../../icons';
import { postMsg } from '../../vscode';
import { useToastStore } from '../../store/toast-store';

interface CookieEntry {
  id: string;
  domain: string;
  name: string;
  value: string;
  path: string;
  expires?: string;
  httpOnly: boolean;
  secure: boolean;
  sameSite: 'Strict' | 'Lax' | 'None';
}

interface Props {
  onClose: () => void;
}

function parseNetscapeCookies(text: string): CookieEntry[] {
  const entries: CookieEntry[] = [];
  for (const line of text.split('\n')) {
    if (line.startsWith('#') || !line.trim()) continue;
    const parts = line.split('\t');
    if (parts.length < 7) continue;
    entries.push({
      id: `cookie-${Date.now()}-${Math.random()}`,
      domain: parts[0].replace(/^\./, ''),
      httpOnly: parts[1] === 'TRUE',
      path: parts[2],
      secure: parts[3] === 'TRUE',
      expires: parts[4] && parts[4] !== '0' ? new Date(Number(parts[4]) * 1000).toISOString() : undefined,
      name: parts[5],
      value: parts[6],
      sameSite: 'Lax',
    });
  }
  return entries;
}

function toNetscapeCookies(cookies: CookieEntry[]): string {
  const lines = ['# Netscape HTTP Cookie File\n# Generated by Daakia\n'];
  for (const c of cookies) {
    const exp = c.expires ? Math.floor(new Date(c.expires).getTime() / 1000) : 0;
    lines.push(`${c.domain}\t${c.httpOnly ? 'TRUE' : 'FALSE'}\t${c.path}\t${c.secure ? 'TRUE' : 'FALSE'}\t${exp}\t${c.name}\t${c.value}`);
  }
  return lines.join('\n');
}

export function CookieManager({ onClose }: Props) {
  const [cookies, setCookies] = useState<CookieEntry[]>([]);
  const [filter, setFilter] = useState('');
  const [showImport, setShowImport] = useState(false);
  const [importText, setImportText] = useState('');
  const [selected, setSelected] = useState<string | null>(null);
  const addToast = useToastStore(s => s.addToast);

  useEffect(() => {
    // Load cookies from extension host
    postMsg({ type: 'cookies:getAll' });
    const handler = (evt: MessageEvent) => {
      const msg = evt.data as Record<string, unknown>;
      if (msg.type === 'cookies:list') {
        setCookies((msg.cookies as CookieEntry[]) || []);
      }
    };
    window.addEventListener('message', handler);
    return () => window.removeEventListener('message', handler);
  }, []);

  const filtered = cookies.filter(c =>
    !filter || c.domain.includes(filter) || c.name.includes(filter)
  );

  const addCookie = () => {
    const newCookie: CookieEntry = {
      id: `cookie-new-${Date.now()}`,
      domain: '', name: '', value: '', path: '/',
      httpOnly: false, secure: false, sameSite: 'Lax',
    };
    setCookies(prev => [...prev, newCookie]);
    setSelected(newCookie.id);
  };

  const deleteCookie = (id: string) => {
    const c = cookies.find(x => x.id === id);
    if (c) postMsg({ type: 'cookies:delete', domain: c.domain, name: c.name });
    setCookies(prev => prev.filter(x => x.id !== id));
    if (selected === id) setSelected(null);
  };

  const updateCookie = (id: string, partial: Partial<CookieEntry>) => {
    setCookies(prev => prev.map(c => c.id === id ? { ...c, ...partial } : c));
  };

  const saveCookie = (id: string) => {
    const c = cookies.find(x => x.id === id);
    if (c) {
      postMsg({ type: 'cookies:set', cookie: c });
      addToast({ type: 'success', message: `Cookie ${c.name} saved` });
    }
  };

  const exportCookies = () => {
    const text = toNetscapeCookies(filtered);
    navigator.clipboard.writeText(text);
    addToast({ type: 'success', message: 'Cookies copied to clipboard (Netscape format)' });
  };

  const importCookies = () => {
    const parsed = parseNetscapeCookies(importText);
    setCookies(prev => [...prev, ...parsed]);
    for (const c of parsed) postMsg({ type: 'cookies:set', cookie: c });
    addToast({ type: 'success', message: `${parsed.length} cookies imported` });
    setShowImport(false);
    setImportText('');
  };

  const selectedCookie = cookies.find(c => c.id === selected);

  const modal = (
    <div className="fixed inset-0 z-50 flex items-center justify-center" style={{ backgroundColor: 'rgba(0,0,0,0.5)' }}>
      <div className="w-[780px] max-h-[90vh] flex flex-col rounded-xl border shadow-2xl"
        style={{ backgroundColor: '#1a1a1f', borderColor: 'var(--color-surface-border)' }}>

        <div className="flex items-center gap-2.5 px-5 py-4 border-b flex-shrink-0" style={{ borderColor: 'var(--color-surface-border)' }}>
          <div className="flex-1">
            <p className="text-[13px] font-semibold text-[var(--color-text-primary)]">Cookie Manager</p>
            <p className="text-[11px] text-[var(--color-text-muted)]">{cookies.length} cookies across all domains</p>
          </div>
          <div className="flex gap-2">
            <button type="button" onClick={exportCookies}
              className="flex items-center gap-1 h-[28px] px-2.5 text-[10.5px] rounded-md border cursor-pointer"
              style={{ borderColor: 'var(--color-surface-border)', color: 'var(--color-text-secondary)' }}>
              <CopyIcon size={10} />Export
            </button>
            <button type="button" onClick={() => setShowImport(true)}
              className="flex items-center gap-1 h-[28px] px-2.5 text-[10.5px] rounded-md border cursor-pointer"
              style={{ borderColor: 'var(--color-surface-border)', color: 'var(--color-text-secondary)' }}>
              Import
            </button>
            <button type="button" onClick={addCookie}
              className="flex items-center gap-1 h-[28px] px-2.5 text-[10.5px] rounded-md cursor-pointer text-white"
              style={{ backgroundColor: 'var(--color-success)' }}>
              <PlusIcon size={10} />Add
            </button>
          </div>
          <button type="button" onClick={onClose} className="w-7 h-7 flex items-center justify-center rounded opacity-50 hover:opacity-100 cursor-pointer">
            <CloseIcon size={12} />
          </button>
        </div>

        <div className="px-4 py-2 border-b flex-shrink-0" style={{ borderColor: 'var(--color-surface-border)' }}>
          <input value={filter} onChange={e => setFilter(e.target.value)}
            className="w-full h-[26px] px-2.5 rounded text-[11px] outline-none"
            placeholder="Filter by domain or name…"
            style={{ backgroundColor: 'var(--color-input-bg)', border: '1px solid var(--color-input-border)', color: 'var(--color-text-primary)' }}
          />
        </div>

        <div className="flex flex-1 min-h-0">
          {/* Cookie list */}
          <div className="w-[280px] flex-shrink-0 border-r overflow-y-auto [scrollbar-gutter:stable]" style={{ borderColor: 'var(--color-surface-border)' }}>
            {filtered.length === 0 && (
              <div className="flex items-center justify-center p-4">
                <p className="text-[11px]" style={{ color: 'var(--color-text-muted)' }}>No cookies found</p>
              </div>
            )}
            {filtered.map(c => (
              <button key={c.id} type="button"
                onClick={() => setSelected(c.id)}
                className="w-full text-left flex items-center gap-2 px-3 py-2.5 border-b cursor-pointer transition-colors"
                style={{
                  borderColor: 'var(--color-surface-border)',
                  backgroundColor: selected === c.id ? 'color-mix(in srgb, var(--color-info) 10%, transparent)' : 'transparent',
                }}>
                <div className="flex-1 min-w-0">
                  <p className="text-[11px] font-medium truncate" style={{ color: 'var(--color-text-primary)' }}>{c.name || '(unnamed)'}</p>
                  <p className="text-[9.5px] truncate" style={{ color: 'var(--color-text-muted)' }}>{c.domain || '(no domain)'}</p>
                </div>
                <button type="button" onClick={e => { e.stopPropagation(); deleteCookie(c.id); }}
                  className="w-5 h-5 flex items-center justify-center opacity-30 hover:opacity-100 cursor-pointer flex-shrink-0">
                  <TrashIcon size={10} />
                </button>
              </button>
            ))}
          </div>

          {/* Cookie detail */}
          <div className="flex-1 overflow-y-auto p-4">
            {!selectedCookie && (
              <div className="flex items-center justify-center h-full">
                <p className="text-[11px]" style={{ color: 'var(--color-text-muted)' }}>Select a cookie to edit</p>
              </div>
            )}
            {selectedCookie && (
              <div className="flex flex-col gap-3">
                {[
                  { label: 'Domain', field: 'domain', type: 'text', placeholder: 'example.com' },
                  { label: 'Name', field: 'name', type: 'text', placeholder: 'session_id' },
                  { label: 'Value', field: 'value', type: 'text', placeholder: 'abc123...' },
                  { label: 'Path', field: 'path', type: 'text', placeholder: '/' },
                  { label: 'Expires (ISO 8601)', field: 'expires', type: 'text', placeholder: '2027-01-01T00:00:00Z' },
                ].map(({ label, field, type, placeholder }) => (
                  <div key={field}>
                    <label className="block text-[11px] font-medium mb-1" style={{ color: 'var(--color-text-secondary)' }}>{label}</label>
                    <input
                      type={type}
                      value={(selectedCookie as unknown as Record<string, unknown>)[field] as string || ''}
                      onChange={e => updateCookie(selectedCookie.id, { [field]: e.target.value } as Partial<CookieEntry>)}
                      placeholder={placeholder}
                      className="w-full h-[26px] px-2.5 rounded text-[11px] outline-none"
                      style={{ backgroundColor: 'var(--color-input-bg)', border: '1px solid var(--color-input-border)', color: 'var(--color-text-primary)' }}
                    />
                  </div>
                ))}

                <div className="flex gap-4">
                  {(['httpOnly', 'secure'] as const).map(field => (
                    <label key={field} className="flex items-center gap-1.5 cursor-pointer">
                      <input type="checkbox" checked={selectedCookie[field]}
                        onChange={e => updateCookie(selectedCookie.id, { [field]: e.target.checked })} />
                      <span className="text-[11px]" style={{ color: 'var(--color-text-secondary)' }}>
                        {field === 'httpOnly' ? 'HttpOnly' : 'Secure'}
                      </span>
                    </label>
                  ))}
                </div>

                <button type="button" onClick={() => saveCookie(selectedCookie.id)}
                  className="h-[30px] px-4 text-[11px] font-medium rounded-md cursor-pointer text-white self-start"
                  style={{ backgroundColor: 'var(--color-success)' }}>
                  Save Cookie
                </button>
              </div>
            )}
          </div>
        </div>

        {/* Import modal */}
        {showImport && (
          <div className="absolute inset-0 bg-black/50 flex items-center justify-center z-10 rounded-xl">
            <div className="w-[480px] rounded-xl border p-5 flex flex-col gap-3"
              style={{ backgroundColor: '#1a1a1f', borderColor: 'var(--color-surface-border)' }}>
              <p className="text-[13px] font-semibold" style={{ color: 'var(--color-text-primary)' }}>Import Cookies</p>
              <p className="text-[11px]" style={{ color: 'var(--color-text-muted)' }}>Paste Netscape format cookies (from browser devtools or curl --cookie-jar)</p>
              <textarea value={importText} onChange={e => setImportText(e.target.value)} rows={8}
                className="w-full px-3 py-2 rounded text-[10.5px] font-mono resize-none outline-none"
                placeholder="# Netscape HTTP Cookie File&#10;.example.com TRUE / FALSE 0 session_id abc123"
                style={{ backgroundColor: 'var(--color-input-bg)', border: '1px solid var(--color-input-border)', color: 'var(--color-text-primary)' }} />
              <div className="flex gap-2 justify-end">
                <button type="button" onClick={() => { setShowImport(false); setImportText(''); }}
                  className="h-[30px] px-3 text-[11px] rounded-md cursor-pointer"
                  style={{ color: 'var(--color-text-secondary)', backgroundColor: 'var(--color-surface-hover)' }}>
                  Cancel
                </button>
                <button type="button" onClick={importCookies} disabled={!importText.trim()}
                  className="h-[30px] px-3 text-[11px] font-medium rounded-md cursor-pointer text-white disabled:opacity-40"
                  style={{ backgroundColor: 'var(--color-info)' }}>
                  Import
                </button>
              </div>
            </div>
          </div>
        )}

        <div className="flex items-center justify-end px-5 py-3 border-t flex-shrink-0" style={{ borderColor: 'var(--color-surface-border)' }}>
          <button type="button" onClick={onClose}
            className="h-[30px] px-4 text-[11px] font-medium rounded-md cursor-pointer bg-[var(--color-surface-hover)] text-[var(--color-text-secondary)]">
            Close
          </button>
        </div>
      </div>
    </div>
  );

  return createPortal(modal, document.body);
}
