#!/usr/bin/env node
/**
 * Recapture wiki screens.
 *
 *   npm run screencapture                 every screen
 *   npm run screencapture -- rest dk8s    those sections
 *   npm run screencapture -- rst03 set07  those screens
 *   npm run screencapture -- --list       what the ids are
 *
 * Ids come from `screen-catalogue.mjs` — five characters, a section and a
 * number — and `plan/daakia_wiki/screen-ids.md` is generated from the same
 * list, so the document cannot describe ids the script will not accept.
 *
 * ── The step that is easy to forget ──
 *
 * `npm run test:e2e` builds the extension but NOT the webview, and the capture
 * driver lives in the webview. Skipping that build means the run uses whatever
 * bundle was there last, so a new capture directive silently does nothing and
 * the run still passes — it writes nine screenshots of the wrong screen. This
 * script always builds the webview first, which is the whole reason it exists
 * rather than a line in a README.
 */
import { execFileSync } from 'child_process';
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { SCREENS, SECTIONS, resolve, sectionOf } from './screen-catalogue.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DOC = join(ROOT, 'plan', 'daakia_wiki', 'screen-ids.md');

const args = process.argv.slice(2);
const flags = new Set(args.filter(a => a.startsWith('--')));
const tokens = args.filter(a => !a.startsWith('--'));

function run(cmd, cmdArgs, env = {}) {
  execFileSync(cmd, cmdArgs, {
    cwd: ROOT,
    stdio: 'inherit',
    shell: process.platform === 'win32',
    env: { ...process.env, ...env },
  });
}

// ── --list ───────────────────────────────────────────────────────────────────

if (flags.has('--list')) {
  let section = null;
  for (const [short, capture, label] of SCREENS) {
    const s = sectionOf(short);
    if (s !== section) { section = s; console.log(`\n  ${section}`); }
    console.log(`    ${short.padEnd(7)} ${label.padEnd(34)} ${capture}`);
  }
  console.log(`\n  ${SCREENS.length} screens. Pass ids or section names.\n`);
  process.exit(0);
}

// ── --write-doc ──────────────────────────────────────────────────────────────

function writeDoc() {
  const lines = [
    '# Wiki screen ids',
    '',
    '> Generated by `scripts/screencapture.mjs --write-doc` from',
    '> `scripts/screen-catalogue.mjs`. Do not hand-edit — add the screen to the',
    '> catalogue and re-run.',
    '',
    'Every screen the wiki shows, with the id you pass to the capture script.',
    '',
    '```',
    'npm run screencapture -- rst03        one screen',
    'npm run screencapture -- rest dk8s    whole sections',
    'npm run screencapture                 everything',
    '```',
    '',
  ];

  let current = null;
  for (const [short, capture, label] of SCREENS) {
    const s = sectionOf(short);
    if (s !== current) {
      current = s;
      lines.push('', `## ${current}`, '',
        '| id | screen | capture file |', '| --- | --- | --- |');
    }
    lines.push(`| \`${short}\` | ${label} | \`${SECTIONS[current].dir}/${capture}.html\` |`);
  }

  lines.push('', `_${SCREENS.length} screens._`, '');
  mkdirSync(dirname(DOC), { recursive: true });
  writeFileSync(DOC, lines.join('\n'), 'utf-8');
  console.log(`wrote ${DOC} (${SCREENS.length} screens)`);
}

if (flags.has('--write-doc')) {
  writeDoc();
  if (tokens.length === 0) process.exit(0);
}

// ── What to capture ──────────────────────────────────────────────────────────

const requested = tokens.length === 0
  ? SCREENS.map(([short, capture, label]) => ({ short, capture, label, section: sectionOf(short) }))
  : tokens.flatMap(t => {
      const hits = resolve(t);
      if (hits.length === 0) {
        console.error(`unknown screen or section: ${t}   (try --list)`);
        process.exit(1);
      }
      return hits;
    });

const bySection = new Map();
for (const screen of requested) {
  if (!bySection.has(screen.section)) bySection.set(screen.section, []);
  bySection.get(screen.section).push(screen);
}

console.log(`\ncapturing ${requested.length} screen(s) across ${bySection.size} suite(s)\n`);

// ── Go ───────────────────────────────────────────────────────────────────────

/* Always, and first. See the note at the top of this file. */
console.log('› building the webview (the capture driver lives in it)');
run('npm', ['run', 'build:webview']);

for (const [section, screens] of bySection) {
  const suite = SECTIONS[section].suite;
  /* Mocha greps test titles, which are `capture <captureId>`. Capture ids in a
     section share a prefix, so a whole section is one alternation and a
     handful of screens is a short one. */
  const grep = screens.length === SCREENS.filter(s => sectionOf(s[0]) === section).length
    ? `Daakia Wiki Capture — ${suite}`
    : `capture (${screens.map(s => s.capture).join('|')})`;

  console.log(`\n› ${section}: ${screens.map(s => s.short).join(' ')}`);
  run('npm', ['run', 'test:e2e'], { TEST_GREP: grep });
}

// ── Compile into the wiki ────────────────────────────────────────────────────

const dirs = [...new Set([...bySection.keys()].map(s => SECTIONS[s].dir))];
console.log('\n› compiling captures into the wiki');
run('node', ['scripts/build-wiki-captures.mjs', ...dirs]);

// ── What actually landed ─────────────────────────────────────────────────────

console.log('');
for (const screen of requested) {
  const file = join(ROOT, 'plan', 'daakia_live', SECTIONS[screen.section].dir, `${screen.capture}.html`);
  if (!existsSync(file)) {
    console.log(`  MISSING  ${screen.short}  ${screen.label}`);
    continue;
  }
  const kb = (readFileSync(file, 'utf-8').length / 1024).toFixed(0);
  console.log(`  ok       ${screen.short.padEnd(7)} ${String(kb).padStart(5)}KB  ${screen.label}`);
}

writeDoc();
console.log('\nRemember: the captures live in the private plan repo (daakia/plan is a junction).\n');
