/**
 * ExportPanel — protocol-aware export for REST, GraphQL, gRPC, SOAP, and Realtime mocks.
 */
import { useState } from 'react';
import type { MockServer } from '../mock-types';

const MOCK_ACCENT = 'var(--color-mock-server)';

type ExportFormat = string; // protocol-specific, see EXPORT_CONFIG

interface ExportOption {
  id: ExportFormat;
  label: string;
  description: string;
  generate: (server: MockServer) => string;
  filename: (server: MockServer) => string;
}

export interface Props {
  protocol?: string;
  server: MockServer;
  onExport: (format: ExportFormat) => void;
}

// ─── REST exports ──────────────────────────────────────────────────────────────

const REST_EXPORTS: ExportOption[] = [
  {
    id: 'nodejs',
    label: 'Node.js HTTP Server',
    description: 'Standalone server using the built-in `http` module — zero dependencies. Run with: node mock-server.js',
    filename: s => 'mock-server.js',
    generate: s => {
      const routes = (s.routes ?? []).map(r => ({ method: r.method, path: r.path, status: r.statusCode, body: r.body, headers: r.headers, delay: r.delay }));
      return `/**
 * Mock Server — Generated by Daakia  |  ${s.name}
 * Routes: ${routes.length}  Port: ${s.port ?? 4000}
 */
const http = require('http');
const ROUTES = ${JSON.stringify(routes, null, 2)};

function match(req) {
  return ROUTES.find(r => (r.method === 'ANY' || r.method === req.method) && req.url.startsWith(r.path));
}
http.createServer((req, res) => {
  const route = match(req);
  if (!route) { res.writeHead(404); res.end('Not found'); return; }
  const send = () => { res.writeHead(route.status, { 'Content-Type': 'application/json', ...route.headers }); res.end(route.body); };
  route.delay > 0 ? setTimeout(send, route.delay) : send();
}).listen(${s.port ?? 4000}, () => console.log('Mock running on http://localhost:${s.port ?? 4000}'));`;
    },
  },
  {
    id: 'wiremock',
    label: 'WireMock JSON',
    description: 'WireMock stub mappings JSON — compatible with WireMock standalone. Place in mappings/ directory.',
    filename: s => 'wiremock-mappings.json',
    generate: s => JSON.stringify({
      mappings: (s.routes ?? []).map(r => ({
        request: { method: r.method === 'ANY' ? 'ANY' : r.method, url: r.path },
        response: { status: r.statusCode, body: r.body, headers: r.headers, ...(r.delay ? { fixedDelayMilliseconds: r.delay } : {}) },
      })),
    }, null, 2),
  },
  {
    id: 'docker',
    label: 'Dockerfile',
    description: 'Dockerfile to containerize the Node.js mock server. Build and run with Docker.',
    filename: s => 'Dockerfile',
    generate: s => `# Daakia Mock Server — ${s.name}
FROM node:18-alpine
WORKDIR /app
COPY mock-server.js .
EXPOSE ${s.port ?? 4000}
CMD ["node", "mock-server.js"]
`,
  },
];

// ─── GraphQL exports ───────────────────────────────────────────────────────────

const GRAPHQL_EXPORTS: ExportOption[] = [
  {
    id: 'graphql-http',
    label: 'graphql-http Server',
    description: 'Standalone GraphQL server using the `graphql-http` package with hardcoded mock resolvers.',
    filename: () => 'mock-graphql-server.js',
    generate: s => `/**
 * GraphQL Mock Server — Generated by Daakia  |  ${s.name}
 * Run: npm install graphql graphql-http && node mock-graphql-server.js
 */
const http = require('http');
const { createHandler } = require('graphql-http/lib/use/node');
const { buildSchema } = require('graphql');

const schema = buildSchema(\`
  type Query {
    health: String
  }
\`);

// TODO: replace with your real schema from the Schema tab

const root = {
  health: () => 'ok',
};

const handler = createHandler({ schema, rootValue: root });

http.createServer((req, res) => {
  if (req.url === '/graphql') return handler(req, res);
  res.writeHead(404); res.end();
}).listen(${s.port ?? 4000}, () =>
  console.log('GraphQL mock running at http://localhost:${s.port ?? 4000}/graphql')
);
`,
  },
  {
    id: 'apollo',
    label: 'Apollo Server',
    description: 'Standalone GraphQL server using Apollo Server 4 with mock resolvers.',
    filename: () => 'mock-apollo-server.js',
    generate: s => `/**
 * Apollo GraphQL Mock — Generated by Daakia  |  ${s.name}
 * Run: npm install @apollo/server graphql && node mock-apollo-server.js
 */
const { ApolloServer } = require('@apollo/server');
const { startStandaloneServer } = require('@apollo/server/standalone');

const typeDefs = \`#graphql
  type Query {
    health: String
  }
\`;

// TODO: replace with your real schema from the Schema tab

const resolvers = {
  Query: {
    health: () => 'ok',
  },
};

async function main() {
  const server = new ApolloServer({ typeDefs, resolvers });
  const { url } = await startStandaloneServer(server, { listen: { port: ${s.port ?? 4000} } });
  console.log('Apollo GraphQL mock at', url);
}
main();
`,
  },
];

// ─── gRPC exports ──────────────────────────────────────────────────────────────

const GRPC_EXPORTS: ExportOption[] = [
  {
    id: 'grpc-js',
    label: 'gRPC Server (@grpc/grpc-js)',
    description: 'Standalone gRPC mock server using @grpc/grpc-js. Returns hardcoded mock responses.',
    filename: () => 'mock-grpc-server.js',
    generate: s => `/**
 * gRPC Mock Server — Generated by Daakia  |  ${s.name}
 * Run: npm install @grpc/grpc-js @grpc/proto-loader && node mock-grpc-server.js
 */
const grpc = require('@grpc/grpc-js');
const protoLoader = require('@grpc/proto-loader');
const path = require('path');

// TODO: point to your .proto file (imported via the Services tab)
const PROTO_PATH = path.join(__dirname, 'service.proto');

const packageDef = protoLoader.loadSync(PROTO_PATH, {
  keepCase: true, longs: String, enums: String, defaults: true, oneofs: true,
});
const proto = grpc.loadPackageDefinition(packageDef);

// Mock handlers — replace with your data
const mockHandlers = {
  // Example: GetUser(call, callback) { callback(null, { id: call.request.id, name: 'Alice' }); }
};

const server = new grpc.Server();
// server.addService(proto.YourService.service, mockHandlers);

server.bindAsync(
  '0.0.0.0:${s.port ?? 50051}',
  grpc.ServerCredentials.createInsecure(),
  (err, port) => {
    if (err) throw err;
    console.log('gRPC mock running on port', port);
  }
);
`,
  },
];

// ─── SOAP exports ──────────────────────────────────────────────────────────────

const SOAP_EXPORTS: ExportOption[] = [
  {
    id: 'soap-node',
    label: 'Node.js SOAP Server',
    description: 'Standalone SOAP mock server returning hardcoded XML envelopes for each operation.',
    filename: () => 'mock-soap-server.js',
    generate: s => `/**
 * SOAP Mock Server — Generated by Daakia  |  ${s.name}
 * Run: npm install soap && node mock-soap-server.js
 * OR use raw HTTP: node mock-soap-server-raw.js (no deps)
 */
const http = require('http');

// Raw HTTP SOAP mock — returns hardcoded SOAP envelopes
// Replace the body with your actual SOAP response XML

const SOAP_RESPONSE = \`<?xml version="1.0" encoding="UTF-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <MockResponse>
      <Result>OK</Result>
    </MockResponse>
  </soap:Body>
</soap:Envelope>\`;

const WSDL = \`<?xml version="1.0"?>
<definitions name="${s.name}"
  xmlns="http://schemas.xmlsoap.org/wsdl/"
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <!-- TODO: paste your WSDL from the WSDL tab here -->
</definitions>\`;

http.createServer((req, res) => {
  if (req.url?.endsWith('?wsdl') || req.url?.endsWith('?WSDL')) {
    res.writeHead(200, { 'Content-Type': 'text/xml' });
    return res.end(WSDL);
  }
  res.writeHead(200, { 'Content-Type': 'text/xml; charset=utf-8' });
  res.end(SOAP_RESPONSE);
}).listen(${s.port ?? 4000}, () =>
  console.log('SOAP mock running at http://localhost:${s.port ?? 4000}')
);
`,
  },
];

// ─── WebSocket exports ─────────────────────────────────────────────────────────

const WEBSOCKET_EXPORTS: ExportOption[] = [
  {
    id: 'ws',
    label: 'WebSocket Server (ws)',
    description: 'Standalone WebSocket mock server using the `ws` npm package. Echoes events back.',
    filename: () => 'mock-ws-server.js',
    generate: s => `/**
 * WebSocket Mock Server — Generated by Daakia  |  ${s.name}
 * Run: npm install ws && node mock-ws-server.js
 */
const { WebSocketServer } = require('ws');

// Mock event handlers — edit to match your event definitions
const MOCK_RESPONSES = {
  // 'event-name': (data) => ({ event: 'response-event', payload: { ...data, processed: true } }),
  'ping': () => ({ event: 'pong', payload: { ts: Date.now() } }),
};

const wss = new WebSocketServer({ port: ${s.port ?? 4000} });

wss.on('connection', (ws) => {
  console.log('Client connected');

  ws.on('message', (raw) => {
    try {
      const msg = JSON.parse(raw.toString());
      const handler = MOCK_RESPONSES[msg.event];
      if (handler) {
        ws.send(JSON.stringify(handler(msg.payload ?? {})));
      } else {
        ws.send(JSON.stringify({ event: 'error', payload: { message: 'Unknown event: ' + msg.event } }));
      }
    } catch {
      ws.send(JSON.stringify({ event: 'error', payload: { message: 'Invalid JSON' } }));
    }
  });

  ws.on('close', () => console.log('Client disconnected'));

  // Send a welcome event on connect
  ws.send(JSON.stringify({ event: 'connected', payload: { serverId: '${s.id}', ts: Date.now() } }));
});

console.log('WebSocket mock running on ws://localhost:${s.port ?? 4000}');
`,
  },
];

// ─── SSE exports ───────────────────────────────────────────────────────────────

const SSE_EXPORTS: ExportOption[] = [
  {
    id: 'sse-node',
    label: 'SSE Server (Node.js built-in)',
    description: 'Standalone Server-Sent Events mock using the built-in http module — zero dependencies.',
    filename: () => 'mock-sse-server.js',
    generate: s => `/**
 * SSE Mock Server — Generated by Daakia  |  ${s.name}
 * Run: node mock-sse-server.js
 * Connect: EventSource('http://localhost:${s.port ?? 4000}/events')
 */
const http = require('http');

// Edit these mock events to match your event definitions
const MOCK_EVENTS = [
  { event: 'update', data: { message: 'Hello from mock', ts: null } },
  { event: 'heartbeat', data: { alive: true } },
];

http.createServer((req, res) => {
  if (req.url === '/events') {
    res.writeHead(200, {
      'Content-Type': 'text/event-stream',
      'Cache-Control': 'no-cache',
      'Connection': 'keep-alive',
      'Access-Control-Allow-Origin': '*',
    });

    let idx = 0;
    const interval = setInterval(() => {
      const evt = MOCK_EVENTS[idx % MOCK_EVENTS.length];
      const payload = { ...evt.data, ts: Date.now() };
      res.write(\`event: \${evt.event}\\ndata: \${JSON.stringify(payload)}\\n\\n\`);
      idx++;
    }, 2000);

    req.on('close', () => clearInterval(interval));
    return;
  }
  res.writeHead(404); res.end();
}).listen(${s.port ?? 4000}, () =>
  console.log('SSE mock running at http://localhost:${s.port ?? 4000}/events')
);
`,
  },
];

// ─── Socket.IO exports ─────────────────────────────────────────────────────────

const SOCKETIO_EXPORTS: ExportOption[] = [
  {
    id: 'socketio',
    label: 'Socket.IO Server',
    description: 'Standalone Socket.IO mock server with mock event handlers.',
    filename: () => 'mock-socketio-server.js',
    generate: s => `/**
 * Socket.IO Mock Server — Generated by Daakia  |  ${s.name}
 * Run: npm install socket.io && node mock-socketio-server.js
 */
const { createServer } = require('http');
const { Server } = require('socket.io');

const httpServer = createServer();
const io = new Server(httpServer, { cors: { origin: '*' } });

io.on('connection', (socket) => {
  console.log('Client connected:', socket.id);

  // Edit these handlers to match your event definitions
  socket.on('message:send', (data) => {
    io.emit('message:broadcast', { id: Date.now().toString(), from: socket.id, ...data });
  });

  socket.on('room:join', (data) => {
    socket.join(data.roomId);
    socket.emit('room:joined', { roomId: data.roomId, members: [] });
  });

  socket.on('disconnect', () => console.log('Client disconnected:', socket.id));

  socket.emit('connected', { socketId: socket.id, ts: Date.now() });
});

httpServer.listen(${s.port ?? 4000}, () =>
  console.log('Socket.IO mock running at http://localhost:${s.port ?? 4000}')
);
`,
  },
];

// ─── MQTT exports ──────────────────────────────────────────────────────────────

const MQTT_EXPORTS: ExportOption[] = [
  {
    id: 'aedes',
    label: 'MQTT Broker (aedes)',
    description: 'Standalone MQTT mock broker using the `aedes` package. Intercepts and auto-responds to subscribed topics.',
    filename: () => 'mock-mqtt-broker.js',
    generate: s => `/**
 * MQTT Mock Broker — Generated by Daakia  |  ${s.name}
 * Run: npm install aedes net && node mock-mqtt-broker.js
 * Connect: mqtt://localhost:${s.port ?? 1883}
 */
const aedes = require('aedes')();
const net = require('net');

// Edit these mock topic handlers to match your topic definitions
const TOPIC_RESPONSES = {
  // 'sensors/+/temperature': (topic, payload) => ({ topic: 'sensors/processed', payload: JSON.stringify({ raw: payload, unit: 'C' }) }),
  'daakia/ping': () => ({ topic: 'daakia/pong', payload: JSON.stringify({ ts: Date.now() }) }),
};

aedes.on('publish', (packet, client) => {
  if (!client) return; // ignore broker-originated messages
  const handler = Object.entries(TOPIC_RESPONSES).find(([t]) => mqttMatch(t, packet.topic));
  if (handler) {
    const { topic, payload } = handler[1](packet.topic, packet.payload.toString());
    aedes.publish({ topic, payload, qos: 0, retain: false, dup: false }, () => {});
  }
});

aedes.on('client', client => console.log('MQTT client connected:', client.id));
aedes.on('clientDisconnect', client => console.log('MQTT client disconnected:', client.id));

function mqttMatch(pattern, topic) {
  const re = pattern.replace(/\\+/g, '[^/]+').replace(/#/, '.*');
  return new RegExp('^' + re + '$').test(topic);
}

net.createServer(aedes.handle).listen(${s.port ?? 1883}, () =>
  console.log('MQTT mock broker running on mqtt://localhost:${s.port ?? 1883}')
);
`,
  },
];

// ─── Protocol → options map ────────────────────────────────────────────────────

function getExportOptions(protocol: string): ExportOption[] {
  const map: Record<string, ExportOption[]> = {
    rest:      REST_EXPORTS,
    graphql:   GRAPHQL_EXPORTS,
    grpc:      GRPC_EXPORTS,
    soap:      SOAP_EXPORTS,
    websocket: WEBSOCKET_EXPORTS,
    sse:       SSE_EXPORTS,
    socketio:  SOCKETIO_EXPORTS,
    mqtt:      MQTT_EXPORTS,
  };
  return map[protocol] ?? REST_EXPORTS;
}

// ─── Component ────────────────────────────────────────────────────────────────

export function ExportPanel({ protocol = 'rest', server, onExport }: Props) {
  const options = getExportOptions(protocol);
  const [selected, setSelected] = useState(options[0].id);
  const [preview, setPreview] = useState('');
  const [copied, setCopied] = useState(false);

  const opt = options.find(o => o.id === selected) ?? options[0];

  const generate = () => setPreview(opt.generate(server));

  const copy = async () => {
    try { await navigator.clipboard.writeText(preview); }
    catch {
      const el = document.createElement('textarea');
      el.value = preview; document.body.appendChild(el); el.select(); document.execCommand('copy'); document.body.removeChild(el);
    }
    setCopied(true); setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="flex flex-col gap-3">
      {/* Format tabs */}
      <div className="flex items-center gap-0 border-b border-[rgba(255,255,255,0.08)]">
        {options.map(o => (
          <button key={o.id} type="button"
            onClick={() => { setSelected(o.id); setPreview(''); }}
            className="h-[32px] px-3 text-[11px] font-medium cursor-pointer transition-colors whitespace-nowrap"
            style={{
              borderBottom: selected === o.id ? `2px solid ${MOCK_ACCENT}` : '2px solid transparent',
              color: selected === o.id ? MOCK_ACCENT : 'var(--color-text-muted)',
              marginBottom: '-1px',
            }}>
            {o.label}
          </button>
        ))}
      </div>

      {/* Description */}
      <p className="text-[10px] text-[var(--color-text-muted)] opacity-70 leading-relaxed">{opt.description}</p>

      {/* Actions */}
      <div className="flex items-center gap-2">
        <button type="button" onClick={generate}
          className="h-[30px] px-4 text-[11px] font-medium rounded cursor-pointer"
          style={{ background: `color-mix(in srgb, ${MOCK_ACCENT} 15%, transparent)`, border: `1px solid color-mix(in srgb, ${MOCK_ACCENT} 30%, transparent)`, color: MOCK_ACCENT }}>
          Generate Preview
        </button>
        <button type="button" onClick={() => onExport(selected)}
          className="h-[30px] px-4 text-[11px] font-medium rounded cursor-pointer"
          style={{ background: `color-mix(in srgb, ${MOCK_ACCENT} 25%, transparent)`, border: `1px solid color-mix(in srgb, ${MOCK_ACCENT} 40%, transparent)`, color: MOCK_ACCENT }}>
          Download {opt.filename(server)}
        </button>
      </div>

      {/* Preview */}
      {preview && (
        <div className="flex flex-col gap-1">
          <div className="flex items-center justify-between">
            <span className="text-[10px] text-[var(--color-text-muted)] font-medium uppercase tracking-wide">Preview — {opt.filename(server)}</span>
            <button type="button" onClick={copy}
              className="h-[22px] px-2 text-[10px] rounded cursor-pointer"
              style={{ color: copied ? 'var(--color-success)' : MOCK_ACCENT, background: `color-mix(in srgb, ${MOCK_ACCENT} 10%, transparent)` }}>
              {copied ? '✓ Copied' : 'Copy'}
            </button>
          </div>
          <pre className="p-3 rounded-lg text-[10px] font-mono text-[var(--color-text-muted)] overflow-auto max-h-[320px] whitespace-pre"
            style={{ background: 'rgba(0,0,0,0.3)', border: '1px solid rgba(255,255,255,0.07)' }}>
            {preview}
          </pre>
        </div>
      )}
    </div>
  );
}
